### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by onaclov2000** [openai/retro#1]
## Issue summary
I'm running on a linux which doesn't have pip3 installed, however the appropriate python 3.5 is installed. I tried copy/pasting the wheel install instructions but I kept getting that the wheel wasn't appropriate for my platform.

After a lot of tail chasing, I realized that pip was for python 2.7 so I had to install (sudo apt-get install python3-pip) and then run the original command with pip3 not pip.

Not sure if this is noteworthy, but was a pain for me to get setup initially.

so this:

    pip install https://storage.googleapis.com/gym-retro/builds/gym_retro-0.5.2-cp35-cp35m-linux_x86_64.whl

became this after installing the appropriate pip:

    pip3 install https://storage.googleapis.com/gym-retro/builds/gym_retro-0.5.2-cp35-cp35m-linux_x86_64.whl

Including Error found for easier searching:

    gym_retro-0.5.2-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform.

## System information

- Ubuntu 16.04
- 3.5.2
- pip install https://storage.googleapis.com/gym-retro/builds/gym_retro-0.5.2-cp35-cp35m-linux_x86_64.whl

**Comment by onaclov2000** [comment]
Just wanting to document some install issues here too for others: I tried inserting this from the user guide but the roms arent installed:

    import retro
    env = retro.make(game='SonicTheHedgehog-Genesis', state='GreenHillZone.Act1')

**Comment by endrift** [comment]
Use the Steam downloader script, it puts the ROMs in the right place. Otherwise you need to use the import script manually.

**Comment by RMKD** [comment]
retro will load roms you already own if they are stored in `site-packages/retro/data/<game-title>/rom.md` (i.e. `.pyenv/versions/3.6.2/lib/python3.6/site-packages/retro/data/SonicAndKnuckles3-Genesis/rom.d`)

**Comment by endrift** [comment]
`RETRO_DATA_PATH` lets you swap out everything from `site-packages/retro/data`, but you still need `<game-title>/rom.md` folder structure. There is currently no way to have the ROMs loose and autodetected.

**Comment by deadpahn** [comment]
I am also having issues with the error in OPs original post.
`gym_retro-0.5.3-cp35-cp35m-linux_x86_64.whl is not a supported wheel on this platform`

I am running linux mint. Currently trying your fix, so far so good.

**Comment by endrift** [comment]
I've updated the documentation to specify the right version of `pip` to use.
