### ISSUE TITLE
Installation failed on Raspberry Pi

### ISSUE THREAD

**Issue by phmignot** [openai/retro#102]
## Issue summary
I have already installed gym-retro on my computer, but I can't install it on a raspberry Pi.

cmake has been installed from source.
setuptools version 40.6.2

I have tried to install gym-retro from source and directly with pip3.
I link you everything since the first warning.

    [ 91%] Building CXX object CMakeFiles/retro-base.dir/src/memory.cpp.o
    /tmp/pip-build-fet82t45/gym-retro/src/memory.cpp: In member function ‘size_t std::hash<Retro::DataType>::operator()(const Retro::DataType&) const’:
    /tmp/pip-build-fet82t45/gym-retro/src/memory.cpp:131:70: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
      return hash<uint32_t>()(*reinterpret_cast<const uint32_t*>(type.type));
                                                                          ^
    [ 91%] Building CXX object CMakeFiles/retro-base.dir/src/movie.cpp.o
    [ 91%] Building CXX object CMakeFiles/retro-base.dir/src/movie-bk2.cpp.o
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/movie-fm2.cpp.o
    In file included from /usr/include/c++/6/map:60:0,
                     from /tmp/pip-build-fet82t45/gym-retro/third-party/json.hpp:53,
                     from /tmp/pip-build-fet82t45/gym-retro/src/coreinfo.cpp:1:
    /usr/include/c++/6/bits/stl_tree.h: In member function ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_hint_unique_pos(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator, const key_type&) [with _Key = std::__cxx11::basic_string<char>; _Val = std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> >; _KeyOfValue = std::_Select1st<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > >; _Compare = std::less<void>; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > >]’:
    /usr/include/c++/6/bits/stl_tree.h:1928:5: note: parameter passing for argument of type ‘std::_Rb_tree<std::__cxx11::basic_string<char>, std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> >, std::_Select1st<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > >, std::less<void>, std::allocator<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > >}’ will change in GCC 7.1
         _Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/script.cpp.o
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/script-lua.cpp.o
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/search.cpp.o
    In file included from /usr/include/c++/6/map:60:0,
                     from /tmp/pip-build-fet82t45/gym-retro/third-party/gtest/googletest/include/gtest/internal/gtest-internal.h:58,
                     from /tmp/pip-build-fet82t45/gym-retro/third-party/gtest/googletest/include/gtest/gtest.h:58,
                     from /tmp/pip-build-fet82t45/gym-retro/src/memory.h:3,
                     from /tmp/pip-build-fet82t45/gym-retro/src/emulator.h:4,
                     from /tmp/pip-build-fet82t45/gym-retro/src/data.h:3,
                     from /tmp/pip-build-fet82t45/gym-retro/src/data.cpp:1:
    /usr/include/c++/6/bits/stl_tree.h: In member function ‘std::pair<std::_Rb_tree_node_base*, std::_Rb_tree_node_base*> std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::_M_get_insert_hint_unique_pos(std::_Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::const_iterator, const key_type&) [with _Key = std::__cxx11::basic_string<char>; _Val = std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> >; _KeyOfValue = std::_Select1st<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > >; _Compare = std::less<void>; _Alloc = std::allocator<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > >]’:
    /usr/include/c++/6/bits/stl_tree.h:1928:5: note: parameter passing for argument of type ‘std::_Rb_tree<std::__cxx11::basic_string<char>, std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> >, std::_Select1st<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > >, std::less<void>, std::allocator<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > > >::const_iterator {aka std::_Rb_tree_const_iterator<std::pair<const std::__cxx11::basic_string<char>, nlohmann::basic_json<> > >}’ will change in GCC 7.1
         _Rb_tree<_Key, _Val, _KeyOfValue, _Compare, _Alloc>::
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /tmp/pip-build-fet82t45/gym-retro/src/search.cpp:491:51: error: ‘T’ does not name a type
     inline void hash_combine(std::size_t& seed, const T& v) {
                                                       ^
    /tmp/pip-build-fet82t45/gym-retro/src/search.cpp: In function ‘void hash_combine(std::size_t&, const int&)’:
    /tmp/pip-build-fet82t45/gym-retro/src/search.cpp:492:12: error: ‘T’ was not declared in this scope
      std::hash<T> hasher;
                ^
    /tmp/pip-build-fet82t45/gym-retro/src/search.cpp:492:13: error: template argument 1 is invalid
      std::hash<T> hasher;
                 ^
    /tmp/pip-build-fet82t45/gym-retro/src/search.cpp:494:27: error: ‘hasher’ cannot be used as a function
      std::size_t a = (hasher(v) ^ seed) * kMul;
                               ^
    /tmp/pip-build-fet82t45/gym-retro/src/search.cpp:495:13: warning: right shift count >= width of type [-Wshift-count-overflow]
      a ^= (a >> 47);
                 ^~
    /tmp/pip-build-fet82t45/gym-retro/src/search.cpp:497:13: warning: right shift count >= width of type [-Wshift-count-overflow]
      b ^= (b >> 47);
                 ^~
    [ 95%] Building CXX object CMakeFiles/retro-base.dir/src/utils.cpp.o
    CMakeFiles/retro-base.dir/build.make:196 : la recette pour la cible « CMakeFiles/retro-base.dir/src/search.cpp.o » a échouée
    make[3]: *** [CMakeFiles/retro-base.dir/src/search.cpp.o] Erreur 1
    make[3]: *** Attente des tâches non terminées....
    In file included from /usr/include/c++/6/vector:69:0,
                     from /tmp/pip-build-fet82t45/gym-retro/third-party/gtest/googletest/include/gtest/gtest.h:56,
                     from /tmp/pip-build-fet82t45/gym-retro/src/memory.h:3,
                     from /tmp/pip-build-fet82t45/gym-retro/src/emulator.h:4,
                     from /tmp/pip-build-fet82t45/gym-retro/src/data.h:3,
                     from /tmp/pip-build-fet82t45/gym-retro/src/data.cpp:1:
    /usr/include/c++/6/bits/vector.tcc: In member function ‘void std::vector<_Tp, _Alloc>::_M_fill_insert(std::vector<_Tp, _Alloc>::iterator, std::vector<_Tp, _Alloc>::size_type, const value_type&) [with _Tp = nlohmann::basic_json<>; _Alloc = std::allocator<nlohmann::basic_json<> >]’:
    /usr/include/c++/6/bits/vector.tcc:449:5: note: parameter passing for argument of type ‘std::vector<nlohmann::basic_json<>, std::allocator<nlohmann::basic_json<> > >::iterator {aka __gnu_cxx::__normal_iterator<nlohmann::basic_json<>*, std::vector<nlohmann::basic_json<>, std::allocator<nlohmann::basic_json<> > > >}’ will change in GCC 7.1
         vector<_Tp, _Alloc>::
         ^~~~~~~~~~~~~~~~~~~
    In file included from /usr/include/c++/6/vector:64:0,
                     from /tmp/pip-build-fet82t45/gym-retro/third-party/gtest/googletest/include/gtest/gtest.h:56,
                     from /tmp/pip-build-fet82t45/gym-retro/src/memory.h:3,
                     from /tmp/pip-build-fet82t45/gym-retro/src/emulator.h:4,
                     from /tmp/pip-build-fet82t45/gym-retro/src/data.h:3,
                     from /tmp/pip-build-fet82t45/gym-retro/src/data.cpp:1:
    /usr/include/c++/6/bits/stl_vector.h: In member function ‘nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::value_type& nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::operator[](nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::size_type) [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long long int; NumberUnsignedType = long long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer]’:
    /usr/include/c++/6/bits/stl_vector.h:1055:2: note: parameter passing for argument of type ‘__gnu_cxx::__normal_iterator<nlohmann::basic_json<>*, std::vector<nlohmann::basic_json<>, std::allocator<nlohmann::basic_json<> > > >’ will change in GCC 7.1
      _M_fill_insert(begin() + __offset, __n, __x);
      ^~~~~~~~~~~~~~
    CMakeFiles/Makefile2:606 : la recette pour la cible « CMakeFiles/retro-base.dir/all » a échouée
    make[2]: *** [CMakeFiles/retro-base.dir/all] Erreur 2
    CMakeFiles/Makefile2:730 : la recette pour la cible « CMakeFiles/retro.dir/rule » a échouée
    make[1]: *** [CMakeFiles/retro.dir/rule] Erreur 2
    Makefile:431 : la recette pour la cible « retro » a échouée
    make: *** [retro] Erreur 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-fet82t45/gym-retro/setup.py", line 90, in <module>
        **kwargs
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-fet82t45/gym-retro/setup.py", line 62, in run
        subprocess.check_call([make_exe, jobs, 'retro'])
      File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/make', '-j4', 'retro']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fet82t45/gym-retro/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-41zgalo_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-fet82t45/gym-retro/

## System information

- Raspbian GNU/Linux 9 (stretch)
- Python 3.5.3
- gym-retro 0.6.1.dev18+g0f82b71

**Comment by phmignot** [comment]
I think it is related to cmake, since i had some troubles to install it. ( I was not able to  install with pip, so i installed it from source).

**Comment by phmignot** [comment]
Since the file src/search.cpp was changed, another error occurs : 

    [100%] Built target retro-base
    [100%] Linking CXX shared library retro/_retro.cpython-35m-arm-linux-gnueabihf.so
    /usr/bin/ld: third-party/luajit/src/libluajit.a(lj_err.o): relocation R_ARM_THM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
    third-party/luajit/src/libluajit.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    CMakeFiles/retro.dir/build.make:87: recipe for target 'retro/_retro.cpython-35m-arm-linux-gnueabihf.so' failed
    make[3]: *** [retro/_retro.cpython-35m-arm-linux-gnueabihf.so] Error 1
    CMakeFiles/Makefile2:735: recipe for target 'CMakeFiles/retro.dir/all' failed
    make[2]: *** [CMakeFiles/retro.dir/all] Error 2
    CMakeFiles/Makefile2:747: recipe for target 'CMakeFiles/retro.dir/rule' failed
    make[1]: *** [CMakeFiles/retro.dir/rule] Error 2
    Makefile:444: recipe for target 'retro' failed
    make: *** [retro] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/labopb/gym-retro/setup.py", line 90, in <module>
        **kwargs
      File "/home/labopb/.local/lib/python3.5/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/labopb/.local/lib/python3.5/site-packages/setuptools/command/develop.py", line 38, in run
        self.install_for_development()
      File "/home/labopb/.local/lib/python3.5/site-packages/setuptools/command/develop.py", line 138, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/labopb/gym-retro/setup.py", line 62, in run
        subprocess.check_call([make_exe, jobs, 'retro'])
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/make', '-j4', 'retro']' returned non-zero exit status 2

Do you have any idea how to solve it ?

**Comment by endrift** [comment]
First issue is a 32-bit build failure, second issue is a LuaJIT build system bug. It can probably be worked around though.

**Comment by phmignot** [comment]
I succeed to install gym-retro and its UI, I install a 64bits OS on the RP. But at the end, it is rather slow.
Thanks.
