### ISSUE TITLE
Sticky Frame Skip

### ISSUE THREAD

**Issue by wilkinsmicawber** [openai/retro#103]
The Gotta Learn Fast Article implemented sticky frameskip. It appears that it would have also been integrated into stable baselines. I can't seem to find it in the code for the rainbow implementation. Is sticky frame skip implemented in the base code?

The article also used regular frameskip, but I can't find it, either. Is frameskip in the baseline implementations?

**Comment by christopherhesse** [comment]
For future reference it's located here: https://github.com/openai/baselines/blob/d80acbb4d1f8b3359c143543dd3f21a3b12679c8/baselines/common/retro_wrappers.py#L219
