### ISSUE TITLE
Travis can no longer build for Mac

### ISSUE THREAD

**Issue by endrift** [openai/retro#106]
## Issue summary

Travis no longer builds bottles for 10.11, which is our minimum target, breaking the build process while it tries to install Qt 5. Checking out the homebrew-core tree to 91279f5a2f81fcbe40842cfb46e74a5683fe21ce may fix this, in combination with the `HOMEBREW_NO_AUTO_UPDATE` env var; alternatively we can drop support for 10.11 and make 10.12 the minimum supported OS.

## System information

- OS X 10.11 on Travis

**Comment by christopherhesse** [comment]
Thanks for looking into this!  Homebrew "requires" 10.12 or higher, and given the fast rate of people dropping support for old OS X versions, I think we can switch to make 10.12 the minimum version.  @endrift do you know what the minimum supported version of windows is for retro?

**Comment by endrift** [comment]
I don't know about the Python module, but the integration UI requires 7 so we might as well just peg it at 7.
