### ISSUE TITLE
Discretize action space in Atari Games?

### ISSUE THREAD

**Issue by simoninithomas** [openai/retro#108]
## Issue summary

Hey there,

I'm currently working in a DQN agent with PyTorch using Space Invaders, however I have some problems:
- The action system in Retro is an array with 1 at each button pressed.
- However, there is too much useless combinations, we just need (for space invaders): Left, Right, Shoot, [Left and shoot], [Right and shoot].

I modified the Sonic Action discretizer:
```
class SpaceInvadersDiscretizer(gym.ActionWrapper):
    """
    Wrap a gym-retro environment and make it use discrete
    actions for the Space Invaders game.
    """
    def __init__(self, env):
        super(SpaceInvadersDiscretizer, self).__init__(env)
        buttons = ["BUTTON", "LEFT", "RIGHT"]
        actions = [["BUTTON"], ['LEFT'], ['RIGHT'], ["BUTTON","LEFT"], ["BUTTON", "RIGHT"]]
        self._actions = []
        """
        What we do in this loop:
        For each action in actions
            - Create an array of 3 False (3 = nb of buttons)
            For each button in action: (for instance ['LEFT']) we need to make that left button index = True
                - Then the button index = LEFT = True
            In fact at the end we will have an array where each array is an action and each elements True of this array
            are the buttons clicked.
        """
        for action in actions:
            arr = np.array([False] * 3)
            for button in action:
                arr[buttons.index(button)] = True
            self._actions.append(arr)
        self.action_space = gym.spaces.Discrete(len(self._actions))

    def action(self, a): # pylint: disable=W0221
        return self._actions[a].copy()
```

And now I have 5 possible actions:
- 0: Shoot (works)
- 1: Left (does not work)
- 2: Right (does not work)
- 3: Left and Shoot (shoot works not left)
- 4: Right and Shoot (shoot works not right)

Do someone knows why?
And does it exists a better way to handle actions with retro?

Thanks!

## System information

- Windows 10
- Python 3.6.4
- Retro 0.5.6

**Comment by endrift** [comment]
The names of the actions are only informational. You need to get the indices mapped properly. This isn't a bug so I'm closing it, but you can keep discussing meanwhile.

**Comment by christopherhesse** [comment]
As endrift implied, you modified the buttons which broke the mapping.  Here's a more generic discretizer: https://gist.github.com/christopherhesse/6ec5ad6e206c3d065e5f8ce11edcda77 note that I used `buttons=env.unwrapped.buttons` since those are determined by the console.  The user sets only the valid `combos` here.
