### ISSUE TITLE
Don't use system libzip

### ISSUE THREAD

**Issue by cwgreene** [openai/retro#11]
## Issue summary

The build can be made more reliable by not attempting to use the system libzip. The build process already downloads libzip into `third_party`, rather than trying to ensure that the installed version of libzip has the interface we expect, just always build the 3p library and consume it.

For example, on Ubuntu 14.04, the file `zip.h` does not contain a definition for `zip_t`. This results in the build failing.

## System information

- [Operating system]
Ubuntu 14.04
- [Python version]
3.6
- [Gym Retro version]
06629f649062fb0bf4e81bb217d8bf01f72d83f6

**Comment by endrift** [comment]
system libzip is now ignored if it's too old.

**Comment by cwgreene** [comment]
Cool; thanks for the explanation and fixing the issue! :)
