### ISSUE TITLE
Where to find 'env.action_space.sample()' actions to the legacy console controller button?

### ISSUE THREAD

**Issue by Christopheraburns** [openai/retro#110]
## Issue summary
[Context]
I am putting some lessons together via a python code wrapper during training of a gym-retro game.

[Question]
Where can I find the mapping between the actions created by the action_space and the target console's (core) controller.

For instance, a Sega Genesis action can be any variation (0 or 1) of the 12 digit array:
[0,0,0,0,0,0,0,0,0,0,0,0] 

12 digits for the 12 buttons of the Sega Controller

Is there documentation that lets me know what the array state is when a controller button is simulated/pressed.

TIA

## System information
Ubuntu 16.04
Python 3.5
Built from source on 1/6/19

**Comment by Christopheraburns** [comment]
gym-retro/cores/genesis.json

not sure how I missed that! Sorry for the unnecessary question.

**Comment by christopherhesse** [comment]
Also check out `env.buttons`
