### ISSUE TITLE
Getting keyboard input from retro.make object?

### ISSUE THREAD

**Issue by tunstek** [openai/retro#113]
## Issue summary

Just wondering if this functionality is available internally.
Essentially I would like control with manual input, much like in the Integration UI.
I'm aware I could probably use curses for this but I'd rather not if I don't have to.

## System information

- Mac OS Mojave (10.14.2)
- Python 3.6.2
- Retro 0.6.0

**Comment by christopherhesse** [comment]
Do you mean like this script here? https://github.com/openai/retro-movies/blob/master/human-recorder.py

**Comment by tunstek** [comment]
Thanks for the link. Yes this is what I'm trying to achieve but is there anyway to attach the pyglet.window.key.KeyStateHandler() to the window created with env.render()? Or must a new window be created?

**Comment by christopherhesse** [comment]
There are some `env.render()` interfaces that allow keyboard input, but they don't let you perform actions in the environment since that's done with `env.step()`.  I'd suggest something like `human-recorder.py`.
