### ISSUE TITLE
Stella set_state seems off

### ISSUE THREAD

**Issue by christopherhesse** [openai/retro#114]
## Issue summary

Stella set_state seems to be a little odd:

```
import retro

for game in sorted(retro.data.list_games()):
    if not game.endswith('-Atari2600'):
        continue

    env = retro.make(game=game)

    act = env.action_space.sample()

    env.reset()
    initial_state = env.em.get_state()
    env.em.set_state(initial_state)
    env.step(act)
    ram1 = env.get_ram()

    env.reset()
    env.step(act)
    ram2 = env.get_ram()

    if not (ram1 == ram2).all():
        print('failed', game)

    env.close()
```

This prints:

```
failed Jamesbond-Atari2600
failed MontezumaRevenge-Atari2600
```

I would expect this to not fail, but I might be using `set_state()` incorrectly.

## System information

- macOS 10.13.6
- Python 3.6.6 :: Anaconda, Inc.
- 0.6.1.dev36+g3305752

**Comment by christopherhesse** [comment]
I think I might be mis-using `set_state()`, closing for now.

**Comment by christopherhesse** [comment]
I made a more elaborate test script: https://gist.github.com/christopherhesse/f5c8cda9ab40e62cdddbc31ff9802594

Here are the failures, ignoring other known issues:

```
failed: AddamsFamily-GameBoy (failed ram)
failed: BakuretsuSenshiWarrior-GameBoy (failed ram)
failed: Jamesbond-Atari2600 (failed ram)
failed: MontezumaRevenge-Atari2600 (failed ram)
failed: Pong-Atari2600 (failed ram)
failed: SuperMarioWorld2-Snes (failed ram)
```

**Comment by christopherhesse** [comment]
Updating stella might fix this.

**Comment by endrift** [comment]
There's a crash in libretro being tracked by https://github.com/libretro/stella-libretro/issues/44. I can try fixing that to see if it also fixes this.

**Comment by christopherhesse** [comment]
Thanks for pushing that fix, but the ram values are still not what my script predicts they should be, so either my script is broken or else there's some stella non-determinism going on.

**Comment by christopherhesse** [comment]
I updated the script to compare to the ALE versions: https://gist.github.com/christopherhesse/c55c1b2e130eea06e45080d092e78951

The results show that ALE passes this test fine, while retro does not:

```
python retro-get-state-set-state.py --pattern "*pong*"
Pong-Atari2600
failed ram
ale:pong
failed: Pong-Atari2600
```

```
python retro-get-state-set-state.py --pattern "*montezuma*"
MontezumaRevenge-Atari2600
failed ram
failed ram
failed ram
ale:montezuma_revenge
failed: MontezumaRevenge-Atari2600
```

Looks like elevator action has some known issues with ALE: https://github.com/openai/gym/blob/master/gym/envs/__init__.py#L445

There's like two different kinds of state restore used in ALE: https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py#L161

**Comment by endrift** [comment]
The second one only works due to them messing around with the internals of Stella, which we haven't done. I looked into this at one point.

**Comment by christopherhesse** [comment]
Ah good to know, so do you think it's likely that all of these are issues with state not being entirely saved by the individual cores?

**Comment by endrift** [comment]
Could be. Or being loaded properly.

**Comment by christopherhesse** [comment]
ALE may not be fully deterministic either: https://github.com/openai/atari-py/issues/28

**Comment by christopherhesse** [comment]
Here's an idea for a deterministic wrapper that may work for non-lua-based scenarios: https://gist.github.com/christopherhesse/fd8a6593df61bafb4af6ef8dcdca11b2

**Comment by christopherhesse** [comment]
Added this to the examples: https://github.com/openai/retro/commit/3d153b9601f5b71b4ca6ed41653ad5f8cff3e4b6

It's unclear why Stella is so slow to restore a state, but GameBoy games hanging is a known issue: https://github.com/openai/retro/issues/116
