### ISSUE TITLE
Adding a Negative Reward Every Step

### ISSUE THREAD

**Issue by batu** [openai/retro#118]
## Issue summary

[Put a detailed description of the issue here.]
I am trying to add a negative reward every step to disincentivize loitering. However I have a hard time getting the scenario to work.

```
{
  "done": {
    "variables": {
      "lives": {
        "op": "equal",
        "reference": 0
      }
    }
  },
  "reward": {
    "time":{
      "penalty":1,
    },
    "variables": {
      "score": {
        "reward": 1
      }
    }
  }
}
```

Here is the code I am working with but I am getting an error that tells me the scenario is not well formed. 

`AssertionError: Failed to load info (/home/batu/anaconda3/lib/python3.6/site-packages/retro/data/stable/SuperMarioWorld-Snes/data.json) or scenario (/home/batu/anaconda3/lib/python3.6/site-packages/retro/data/stable/SuperMarioWorld-Snes/scenario.json)
`

Can anyone who has used the timer under reward give me so heads up as to what I am doing wrong?

Thank you very much.

I do not think this information is salient for this case but:
Ubuntu 16.04
retro 0.6.0
python 3.6

**Comment by endrift** [comment]
You have a trailing comma for the penalty, which is causing the JSON to fail to load.
