### ISSUE TITLE
Manually setting the episode length without using a counter in the training loop

### ISSUE THREAD

**Issue by batu** [openai/retro#120]
## Issue summary
I apologize if this is mentioned somewhere in the documentation but I couldn't figure it out just yet.

I want to manually set the episode length for my runs to a specific timestep (without making it related to any of the bytes in memory). Given my set up, having an external counter to reset it manually is not feasable. 

What is the preferred way of doing it via the specifications in scenario.json? The default for Super Mario World seems to be set to 12800, or a multiple of it if my initial skim isn't wrong. Where is that defined?

**Comment by endrift** [comment]
This is done using a wrapper environment. It's not supported in retro itself.

**Comment by batu** [comment]
Noted. Thank you!
