### ISSUE TITLE
Pressing Start or Select Button for SNES Games?

### ISSUE THREAD

**Issue by AurelianTactics** [openai/retro#125]
## Issue summary

I have a SNES game where at the end of the level, in order to finish the level the start button has to be pressed. The agent can reach the end of the level but never hits start and the episode times out. I tried to get the agent to hit START or SELECT and I'm not sure if the agent does. I can't confirm START or SELECT pressing in video recordings of the episode while I can for every other SNES button.

I wrote a function similar to the SonicDiscretizer (https://github.com/openai/baselines/blob/d80acbb4d1f8b3359c143543dd3f21a3b12679c8/baselines/common/retro_wrappers.py) except for SNES games. Ie I replace the buttons for Sega with SNES keys:
```
class ContraDiscretizer(gym.ActionWrapper):
    def __init__(self, env):
        super(ContraDiscretizer, self).__init__(env)
        # SNES keys
        buttons = ["B", "Y", "SELECT", "START", "UP", "DOWN", "LEFT", "RIGHT", "A", "X", "L", "R"]

        #start test
        actions = [["SELECT"],["START"]]

        self._actions = []
        for action in actions:
            arr = np.array([False] * 12)
            for button in action:
                arr[buttons.index(button)] = True
                print("appending button in action {} in {}".format(button,action))
                print(arr,buttons.index(button))
            self._actions.append(arr)
        print("final self._actions are {}".format(self._actions))
        self.action_space = gym.spaces.Discrete(len(self._actions))

    def action(self, a): # pylint: disable=W0221
        print(" in action a is {} self._actions[a] is ".format(a,self._actions[a].copy()))
        return self._actions[a].copy()
```
As you can see, in the action() function I have a print statement. Actions for start and select register through there and when I add another action like UP or RIGHT those actions register too. However when I watch videos of those replays (using the MovieRecord wrapper) the START and SELECT actions don't register. The SELECT button doesn't do anything in the SNES game but START should pause the game. That doesn't show up in the videos. If I do movie.step() and print out the movie.get_key() every step, keys for actions like UP and RIGHT show up but START and SELECT don't (returns all FALSE values). 

If I modify the allowed actions to multi button presses that include START or SELECT the other button will be pressed and this will register on the video and in the pressed movie.get_key() but START and SELECT will not.

`actions = [["SELECT","Y"], ["START","B"]]`

Ie the video will show the Y or B key being pressed but still disregards the SELECT and START keys.

## System information

- Ubuntu 16.04
- 3.6
- 0.6.0

**Comment by christopherhesse** [comment]
Are you creating the environment with `use_restricted_actions=retro.Actions.ALL` (https://github.com/openai/retro/blob/master/retro/__init__.py#L25) ?  If not, you'll only get filtered actions.  The normal way to make this work with the default filtered actions is to allow start and select in the scenario.json.  `KidChameleon-Genesis` requires allowing the start button here: https://github.com/openai/retro/blob/master/retro/data/stable/KidChameleon-Genesis/scenario.json#L19

**Comment by AurelianTactics** [comment]
Ah sorry, my mistake, I was using retro.Actions.FILTERED. Setting it to retro.Actions.ALL allows START and SELECT. I didn't realize that FILTERED worked like that.

**Comment by endrift** [comment]
That's part of the intent of it. We should document that better.
