### ISSUE TITLE
pip3 install -e .

### ISSUE THREAD

**Issue by ggiallo28** [openai/retro#13]
## Issue summary
Installation Error when I try to execute pip3 install -e .

Installing collected packages: gym-retro
  Found existing installation: gym-retro 0.5.2
    Uninstalling gym-retro-0.5.2:
      Successfully uninstalled gym-retro-0.5.2
  Running setup.py develop for gym-retro
    Complete output from command /usr/local/opt/python/bin/python3.6 -c "import setuptools, tokenize;__file__='/Users/gianluigimucciolo/Repositories/Contest/gym-retro/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps:
    running develop
    running egg_info
    writing gym_retro.egg-info/PKG-INFO
    writing dependency_links to gym_retro.egg-info/dependency_links.txt
    writing requirements to gym_retro.egg-info/requires.txt
    writing top-level names to gym_retro.egg-info/top_level.txt
    package init file 'data/__init__.py' not found (or not a regular file)
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*.o' found anywhere in distribution
    warning: no previously-included files matching '*.a' found anywhere in distribution
    warning: no previously-included files matching '*.dylib' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*-version' found under directory 'retro/cores'
    writing manifest file 'gym_retro.egg-info/SOURCES.txt'
    running build_ext
    error: [Errno 2] No such file or directory: 'cmake': 'cmake'
    
    ----------------------------------------
  Rolling back uninstall of gym-retro
Command "/usr/local/opt/python/bin/python3.6 -c "import setuptools, tokenize;__file__='/Users/gianluigimucciolo/Repositories/Contest/gym-retro/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in /Users/gianluigimucciolo/Repositories/Contest/gym-retro/

## System information

- macOS Sierra 10.13.3
- Python 3.6.5
- gym-retro 0.5.2

**Comment by endrift** [comment]
You need to install CMake, as noted in the readme.

**Comment by jithinjk** [comment]
I've installed CMake. But getting similar issue.

```
$ cmake --version
cmake version 3.11.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by sophiaonion** [comment]
I encountered this error on the same macOS as well. I pulled the retro game github repo, changed to the directory, and was able to install `cmake` after changing directory.

**Comment by endrift** [comment]
I've added code to automatically download and use the CMake wheel if CMake can't be found.
