### ISSUE TITLE
integration tool cmake error

### ISSUE THREAD

**Issue by MatPoliquin** [openai/retro#130]
I get an error generating the makefile for the integration tool:

Command:
**cmake . -DBUILD_UI=ON -UPYLIB_DIRECTORY**
log:
-- Submodules seem to be missing. Attempting to clone now.
Submodule 'atari2600' (https://github.com/libretro/stella-libretro.git) registered for path 'cores/atari2600'
Submodule 'gb' (https://github.com/libretro/gambatte-libretro.git) registered for path 'cores/gb'
Submodule 'gba' (https://github.com/libretro/mgba.git) registered for path 'cores/gba'
Submodule 'genesis' (https://github.com/libretro/Genesis-Plus-GX.git) registered for path 'cores/genesis'
Submodule 'nes' (https://github.com/libretro/libretro-fceumm.git) registered for path 'cores/nes'
Submodule 'pce' (https://github.com/libretro/beetle-pce-fast-libretro.git) registered for path 'cores/pce'
Submodule 'snes' (https://github.com/libretro/snes9x.git) registered for path 'cores/snes'
Submodule 'third-party/capnproto' (https://github.com/capnproto/capnproto.git) registered for path 'third-party/capnproto'
Submodule 'gtest' (https://github.com/google/googletest.git) registered for path 'third-party/gtest'
Submodule 'third-party/libzip' (https://github.com/nih-at/libzip.git) registered for path 'third-party/libzip'
Submodule 'third-party/luajit' (http://luajit.org/git/luajit-2.0.git) registered for path 'third-party/luajit'
Submodule 'third-party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'third-party/pybind11'
Cloning into '/home/p108/ML/retro/cores/atari2600'...
Cloning into '/home/p108/ML/retro/cores/gb'...
Cloning into '/home/p108/ML/retro/cores/gba'...
Cloning into '/home/p108/ML/retro/cores/genesis'...
Cloning into '/home/p108/ML/retro/cores/nes'...
Cloning into '/home/p108/ML/retro/cores/pce'...
Cloning into '/home/p108/ML/retro/cores/snes'...
Cloning into '/home/p108/ML/retro/third-party/capnproto'...
Cloning into '/home/p108/ML/retro/third-party/gtest'...
Cloning into '/home/p108/ML/retro/third-party/libzip'...
Cloning into '/home/p108/ML/retro/third-party/luajit'...
Cloning into '/home/p108/ML/retro/third-party/pybind11'...
Submodule path 'cores/atari2600': checked out 'b0b63615fc2c7a30470fc1ac31ffdc18fdf4518b'
Submodule path 'cores/gb': checked out '4b98cd4d8ad13de9e08fe583ed814f76d800a0d1'
Submodule path 'cores/gba': checked out '92fe6845d25d5322510f1005f17f8818b8550df4'
Submodule path 'cores/genesis': checked out 'f66bcb1e780acdcced95a05e04550bb8a91c1850'
Submodule path 'cores/nes': checked out 'fdf6993b6cd68e62e03d1c7cc0e87ed3ee7e0483'
Submodule path 'cores/pce': checked out '35e96c44b6d43c8ff48d5484331ecdd9ad4dfc03'
Submodule path 'cores/snes': checked out '05cb2edcf9d3fae8e77726ce5b7964e81ba18ad8'
Submodule path 'third-party/capnproto': checked out 'c949a18da5f041a36cc218c5c4b79c7705999b4f'
Submodule path 'third-party/gtest': checked out 'b7e8a993b4125d1083cb431d91407d8ee4dba2ad'
Submodule path 'third-party/libzip': checked out 'ab882fdd77c85f6c4723543b0d054943420a2786'
Submodule path 'third-party/luajit': checked out '8271c643c21d1b2f344e339f559f2de6f3663191'
Submodule path 'third-party/pybind11': checked out '8edc147d67ca85a93ed1f53628004528dc36a04d'
-- Submodules cloned!
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
CMake Error at CMakeLists.txt:23 (project):
  VERSION "0.7.0

  " format invalid.

-- Configuring incomplete, errors occurred!

## System information
Ubuntu 18.10
with latest retro repo commit

I can run openai baselines with retro environments without problems.

**Comment by MatPoliquin** [comment]
I just found the cause. There is an extra line in the "VERSION" file. Once removed it works.
I will make a pull request

**Comment by christopherhesse** [comment]
Should be fixed in master, thanks for the bug report!
