### ISSUE TITLE
Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported

### ISSUE THREAD

**Issue by auscar92** [openai/retro#132]
## Issue summary
So I've been trying to set up gym-retro, and I got past the pip3 install -e . step, and after trying the next step, running ./gym-retro-integration
this error comes up
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-auscar92'
failed to get the current screen resources
WARNING: Application calling GLX 1.3 function "glXCreatePbuffer" when GLX 1.3 is not supported!  This is an application bug!
QXcbConnection: XCB error: 170 (Unknown), sequence: 170, resource id: 90, major code: 146 (Unknown), minor code: 20
along with an Xming X window.  I tried uninstalling Xming but the installation couldn't be completed all the way.
I really appreciate the help, I've been looking at some other similar errors with gym not displaying, and this was as close as I could get
## System information

- Windows 10, with Ubuntu 1804 subsystem
- Python 2.7
- gym-retro 0.7.0

**Comment by endrift** [comment]
Using Gym Retro Integration inside of WSL isn't supported, since there's a Windows version: 
https://storage.googleapis.com/gym-retro/builds/Gym%20Retro-0.7.0.dev58%2Bg48be026-win64.zip

This sounds like a Qt issue anyway, since we don't call that directly.

**Comment by MatPoliquin** [comment]
> Using Gym Retro Integration inside of WSL isn't supported, since there's a Windows version: https://storage.googleapis.com/gym-retro/builds/Gym%20Retro-0.7.0.dev58%2Bg48be026-win64.zip
> 
> This sounds like a Qt issue anyway, since we don't call that directly.

The link is down and cant find the pre-built windows version elsewhere
