### ISSUE TITLE
cmake error "Qt5Gui"

### ISSUE THREAD

**Issue by MatPoliquin** [openai/retro#133]
When generating the makefile with:
```
cmake . -DBUILD_UI=ON -UPYLIB_DIRECTORY
```

I get this error message:
```
CMake Error at src/ui/CMakeLists.txt:1 (find_package):
  By not providing "FindQt5Gui.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Gui", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Gui" with any
  of the following names:

    Qt5GuiConfig.cmake
    qt5gui-config.cmake

  Add the installation prefix of "Qt5Gui" to CMAKE_PREFIX_PATH or set
  "Qt5Gui_DIR" to a directory containing one of the above files.  If "Qt5Gui"
  provides a separate development package or SDK, be sure it has been
  installed.
```
Is this a bug or now we need to set those variables ourselves?

Before cmake was generating fine (at least until February 19), this is a new error but unfortunately I did not have the time to track down with which commit this error was introduced

## System information
Ubuntu 18.10
Python 3.6.7

**Comment by christopherhesse** [comment]
It doesn't look like we changed anything substantial in `CMakeLists.txt`, are you sure it's not something on your machine?

**Comment by endrift** [comment]
Are you sure the qt5 dev packages are installed?

**Comment by MatPoliquin** [comment]
Yes, qt5 frv is installed. Did not find the cause yet, but I will assume it's on my side since it seems no one else has this error, I will close the issue for now. Thanks

**Comment by KulaGGin** [comment]
So how did you fix this? I have the same error but in other project. I have qt5 installed.
