### ISSUE TITLE
AttributeError: module 'retro' has no attribute 'make'

### ISSUE THREAD

**Issue by ruifengma** [openai/retro#135]
## Issue summary

I just installed gym-retro step by step follow the instruction and run the example code
`import retro
env = retro.make(game='AirStriker-Genesis')`
and I got the error
`AttributeError: module 'retro' has no attribute 'make'`

## System information

-  MacOS Mojave
-  Python 3.6
-  Retro 0.6.0

**Comment by christopherhesse** [comment]
Do you have another package called retro installed or a folder in the current directory called retro?

**Comment by endrift** [comment]
I don't know if you did this (I assume not, given the summary) but note that `pip install retro` will install the wrong package.

**Comment by ruifengma** [comment]
> Do you have another package called retro installed or a folder in the current directory called retro?

No, I checked and there is not another package call retro

**Comment by ruifengma** [comment]
> I don't know if you did this (I assume not, given the summary) but note that `pip install retro` will install the wrong package.

No, I followed the installation guidance in the main page

**Comment by christopherhesse** [comment]
What's the output of `pip show retro`?

**Comment by ruifengma** [comment]
> What's the output of `pip show retro`?

There is actually no reaction once I did that

**Comment by ruifengma** [comment]
> What's the output of `pip show retro`?

but 'pip3 show gym-retro' this gives the information on retro

**Comment by endrift** [comment]
What does this print:
```python
import retro
print(retro.__dict__)
```

**Comment by ruifengma** [comment]
> ```python
> import retro
> print(retro.__dict__)
> ```

it prints
`{'__name__': 'retro', '__doc__': None, '__package__': 'retro', '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x1107eff28>, '__spec__': ModuleSpec(name='retro', loader=<_frozen_importlib_external.SourceFileLoader object at 0x1107eff28>, origin='/Users/ruifengma/Code/gym-retro/gym-retro/retro/__init__.py', submodule_search_locations=['/Users/ruifengma/Code/gym-retro/gym-retro/retro']), '__path__': ['/Users/ruifengma/Code/gym-retro/gym-retro/retro'], '__file__': '/Users/ruifengma/Code/gym-retro/gym-retro/retro/__init__.py', '__cached__': '/Users/ruifengma/Code/gym-retro/gym-retro/retro/__pycache__/__init__.cpython-36.pyc', '__builtins__': {'__name__': 'builtins', '__doc__': "Built-in functions, exceptions, and other objects.\n\nNoteworthy: None is the `nil' object; Ellipsis represents `...' in slices.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'callable': <built-in function callable>, 'chr': <built-in function chr>, 'compile': <built-in function compile>, 'delattr': <built-in function delattr>, 'dir': <built-in function dir>, 'divmod': <built-in function divmod>, 'eval': <built-in function eval>, 'exec': <built-in function exec>, 'format': <built-in function format>, 'getattr': <built-in function getattr>, 'globals': <built-in function globals>, 'hasattr': <built-in function hasattr>, 'hash': <built-in function hash>, 'hex': <built-in function hex>, 'id': <built-in function id>, 'input': <built-in function input>, 'isinstance': <built-in function isinstance>, 'issubclass': <built-in function issubclass>, 'iter': <built-in function iter>, 'len': <built-in function len>, 'locals': <built-in function locals>, 'max': <built-in function max>, 'min': <built-in function min>, 'next': <built-in function next>, 'oct': <built-in function oct>, 'ord': <built-in function ord>, 'pow': <built-in function pow>, 'print': <built-in function print>, 'repr': <built-in function repr>, 'round': <built-in function round>, 'setattr': <built-in function setattr>, 'sorted': <built-in function sorted>, 'sum': <built-in function sum>, 'vars': <built-in function vars>, 'None': None, 'Ellipsis': Ellipsis, 'NotImplemented': NotImplemented, 'False': False, 'True': True, 'bool': <class 'bool'>, 'memoryview': <class 'memoryview'>, 'bytearray': <class 'bytearray'>, 'bytes': <class 'bytes'>, 'classmethod': <class 'classmethod'>, 'complex': <class 'complex'>, 'dict': <class 'dict'>, 'enumerate': <class 'enumerate'>, 'filter': <class 'filter'>, 'float': <class 'float'>, 'frozenset': <class 'frozenset'>, 'property': <class 'property'>, 'int': <class 'int'>, 'list': <class 'list'>, 'map': <class 'map'>, 'object': <class 'object'>, 'range': <class 'range'>, 'reversed': <class 'reversed'>, 'set': <class 'set'>, 'slice': <class 'slice'>, 'staticmethod': <class 'staticmethod'>, 'str': <class 'str'>, 'super': <class 'super'>, 'tuple': <class 'tuple'>, 'type': <class 'type'>, 'zip': <class 'zip'>, '__debug__': True, 'BaseException': <class 'BaseException'>, 'Exception': <class 'Exception'>, 'TypeError': <class 'TypeError'>, 'StopAsyncIteration': <class 'StopAsyncIteration'>, 'StopIteration': <class 'StopIteration'>, 'GeneratorExit': <class 'GeneratorExit'>, 'SystemExit': <class 'SystemExit'>, 'KeyboardInterrupt': <class 'KeyboardInterrupt'>, 'ImportError': <class 'ImportError'>, 'ModuleNotFoundError': <class 'ModuleNotFoundError'>, 'OSError': <class 'OSError'>, 'EnvironmentError': <class 'OSError'>, 'IOError': <class 'OSError'>, 'EOFError': <class 'EOFError'>, 'RuntimeError': <class 'RuntimeError'>, 'RecursionError': <class 'RecursionError'>, 'NotImplementedError': <class 'NotImplementedError'>, 'NameError': <class 'NameError'>, 'UnboundLocalError': <class 'UnboundLocalError'>, 'AttributeError': <class 'AttributeError'>, 'SyntaxError': <class 'SyntaxError'>, 'IndentationError': <class 'IndentationError'>, 'TabError': <class 'TabError'>, 'LookupError': <class 'LookupError'>, 'IndexError': <class 'IndexError'>, 'KeyError': <class 'KeyError'>, 'ValueError': <class 'ValueError'>, 'UnicodeError': <class 'UnicodeError'>, 'UnicodeEncodeError': <class 'UnicodeEncodeError'>, 'UnicodeDecodeError': <class 'UnicodeDecodeError'>, 'UnicodeTranslateError': <class 'UnicodeTranslateError'>, 'AssertionError': <class 'AssertionError'>, 'ArithmeticError': <class 'ArithmeticError'>, 'FloatingPointError': <class 'FloatingPointError'>, 'OverflowError': <class 'OverflowError'>, 'ZeroDivisionError': <class 'ZeroDivisionError'>, 'SystemError': <class 'SystemError'>, 'ReferenceError': <class 'ReferenceError'>, 'BufferError': <class 'BufferError'>, 'MemoryError': <class 'MemoryError'>, 'Warning': <class 'Warning'>, 'UserWarning': <class 'UserWarning'>, 'DeprecationWarning': <class 'DeprecationWarning'>, 'PendingDeprecationWarning': <class 'PendingDeprecationWarning'>, 'SyntaxWarning': <class 'SyntaxWarning'>, 'RuntimeWarning': <class 'RuntimeWarning'>, 'FutureWarning': <class 'FutureWarning'>, 'ImportWarning': <class 'ImportWarning'>, 'UnicodeWarning': <class 'UnicodeWarning'>, 'BytesWarning': <class 'BytesWarning'>, 'ResourceWarning': <class 'ResourceWarning'>, 'ConnectionError': <class 'ConnectionError'>, 'BlockingIOError': <class 'BlockingIOError'>, 'BrokenPipeError': <class 'BrokenPipeError'>, 'ChildProcessError': <class 'ChildProcessError'>, 'ConnectionAbortedError': <class 'ConnectionAbortedError'>, 'ConnectionRefusedError': <class 'ConnectionRefusedError'>, 'ConnectionResetError': <class 'ConnectionResetError'>, 'FileExistsError': <class 'FileExistsError'>, 'FileNotFoundError': <class 'FileNotFoundError'>, 'IsADirectoryError': <class 'IsADirectoryError'>, 'NotADirectoryError': <class 'NotADirectoryError'>, 'InterruptedError': <class 'InterruptedError'>, 'PermissionError': <class 'PermissionError'>, 'ProcessLookupError': <class 'ProcessLookupError'>, 'TimeoutError': <class 'TimeoutError'>, 'open': <built-in function open>, 'quit': Use quit() or Ctrl-D (i.e. EOF) to exit, 'exit': Use exit() or Ctrl-D (i.e. EOF) to exit, 'copyright': Copyright (c) 2001-2018 Python Software Foundation.
All Rights Reserved.

Copyright (c) 2000 BeOpen.com.
All Rights Reserved.

Copyright (c) 1995-2001 Corporation for National Research Initiatives.
All Rights Reserved.

Copyright (c) 1991-1995 Stichting Mathematisch Centrum, Amsterdam.
All Rights Reserved., 'credits':     Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information., 'license': Type license() to see the full license text, 'help': Type help() for interactive help, or help(object) for help about object., '__pybind11_internals_v1__': <capsule object NULL at 0x1107ff450>}, 'os': <module 'os' from '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py'>, '_retro': <module 'retro._retro' from '/Users/ruifengma/Code/gym-retro/gym-retro/retro/_retro.cpython-36m-darwin.so'>, 'data': <module 'retro.data' from '/Users/ruifengma/Code/gym-retro/gym-retro/retro/data/__init__.py'>, 'retro': <module 'retro' from '/Users/ruifengma/Code/gym-retro/gym-retro/retro/__init__.py'>, 'Enum': <enum 'Enum'>, 'Movie': <class 'retro._retro.Movie'>, 'RetroEmulator': <class 'retro._retro.RetroEmulator'>, 'core_path': <built-in method core_path of PyCapsule object at 0x110833a20>, 'ROOT_DIR': '/Users/ruifengma/Code/gym-retro/gym-retro/retro', 'path': 'VERSION.txt', 'f': <_io.TextIOWrapper name='/Users/ruifengma/Code/gym-retro/gym-retro/retro/VERSION.txt' mode='r' encoding='UTF-8'>, '__version__': '0.7.0.dev58+g48be026', '__all__': ['Movie', 'RetroEmulator', 'Actions', 'State', 'get_core_path', 'get_romfile_system', 'get_system_info', 'make'], 'Actions': <enum 'Actions'>, 'State': <enum 'State'>, 'Observations': <enum 'Observations'>, 'get_core_path': <function get_core_path at 0x110826268>, 'get_romfile_system': <function get_romfile_system at 0x110623ae8>, 'get_system_info': <function get_system_info at 0x110668510>, 'make': <function make at 0x10f482c80>}

Process finished with exit code 0
`

**Comment by ruifengma** [comment]
It's eventually works for me, make mistakes on making two 'gym-retro' folder and create a python file called 'retro' which is confusing, after removing it, the problem has been solved, thanks for the advices from christopherhesse and endrift
