### ISSUE TITLE
Sonic Action Space Help

### ISSUE THREAD

**Issue by slerman12** [openai/retro#139]
Hi, I just need help understanding the Sonic action space. Would it be enough just to use `env.env.action_space.n` and use one-hot representations the way one would for CartPole in standard Gym? If not, how do I integrate Sonic's action space into my deep learning setup to enable me to output actions and feed them to the environment?

**Comment by christopherhesse** [comment]
If you don't want to support the MultiBinary space, you can pass `use_restricted_actions=retro.Actions.DISCRETE` or you can use something like https://github.com/openai/retro-baselines/blob/master/agents/sonic_util.py#L24 to get fewer discrete actions, tailored to sonic.

**Comment by slerman12** [comment]
Could you show me example code of how to use that? I wish an example agent existed that didn't just sample actions randomly so I could see in code how to feed actions to the environment.

**Comment by christopherhesse** [comment]
The brute example does this: https://github.com/openai/retro/blob/master/retro/examples/brute.py
