### ISSUE TITLE
module 'retro' has no attribute 'Observations'

### ISSUE THREAD

**Issue by chenyucheng2016** [openai/retro#142]
## Issue summary

[We I run python3 random_agent.py, I have this error]

## System information

- [macOS 10.13]
- [Python 3.7]
- [Don't know how to check. Downloaded at 03/12/19]

**Comment by christopherhesse** [comment]
Hi! Could you paste the full error including the stack trace, as well as the output of:

```
import retro
print(retro.__dict__)
```

**Comment by chenyucheng2016** [comment]
Thank you for your reply! 
The output of print(retro.__dict__) is in the follow txt file.
[retro.__dict.txt](https://github.com/openai/retro/files/2959141/retro.__dict.txt)

The stack trace of the error is:
python3 random_agent.py 
Traceback (most recent call last):
  File "random_agent.py", line 17, in <module>
    obs_type = retro.Observations.IMAGE if args.obs_type == 'image' else retro.Observations.RAM
AttributeError: module 'retro' has no attribute 'Observations'

I solved the problem by commenting out all the variables relavent to obs_type

Also, do you have a documentation for retro? I have a hard time in understanding all the methods and variables.

Thanks!

**Comment by endrift** [comment]
You're using 0.6.0. The Observations enum was added afterwards and is not yet in a stable version.

**Comment by chenyucheng2016** [comment]
Thanks! Do you have a documentation for the repo or could you please tell me where to learn the structures of inputs and outputs of all methods so that I could learn the repo more conveniently?

**Comment by christopherhesse** [comment]
We are looking at adding better documentation in the future.  I'll release a new version at some point so that the scripts work with the latest released binary.  Sorry about that!

**Comment by christopherhesse** [comment]
New documentation is up: https://retro.readthedocs.io/en/latest/index.html

There will be a new release of version 0.7.0 soon.
