### ISSUE TITLE
Can't load from state gameboy emulation

### ISSUE THREAD

**Issue by tylerroost** [openai/retro#144]
## Issue summary

when I try to start an environment from a start state it just starts from the default state. I used gambatte and saved a state, renamed it as a state file, then gzipped it, but it just doesn't seem to want to load. If anyone has any experience with custom roms and their states for gameboy emulation I would greatly appreciate some help

## System information

- Windows 10
- python 3.6
- Gym retro 0.6.0

**Comment by tylerroost** [comment]
I have tried both saving the save state from gambatte as a .state file then gzipping, as well as saving the state as a .gqs file gzipping that and then renaming to a .state file, both methods seem to fail

**Comment by christopherhesse** [comment]
You should generate the state with gym retro and not gambatte.  You can use the integration UI for this: https://github.com/openai/retro#integration-user-interface
