### ISSUE TITLE
IntegrationUI.exe does not work

### ISSUE THREAD

**Issue by tylerroost** [openai/retro#145]
When I try to run the exe it says could not find data directory. Integration and movie loading will not work properly

When I try clicking on the tabs at the top of the IntegrationUI it does nothing

[Put a detailed description of the issue here.]

## System information

-  Windows 10
- python 3.6 unneeded probably
- Gym Retro 0.6.0

**Comment by tylerroost** [comment]
I didn't have it in the same file as my data folder

**Comment by dotunadegbite** [comment]
I have the same error and I'm not sure what you mean by data folder?
