### ISSUE TITLE
Actions are a bit confusing

### ISSUE THREAD

**Issue by christopherhesse** [openai/retro#149]
I expected discrete actions to be filtered and actually wrote this in the docs but that doesn't appear to be the case.  Seems like the interesting action spaces are: filtered multibinary (default), unfiltered multibinary (for replays), and filtered discrete (for approaches that require discrete actions).

One approach would be to split filtering from the specific action space being used, so `use_filtered_actions=True/False` and then `act_type=Multibinary,Discrete`

**Comment by endrift** [comment]
Discrete actions SHOULD be filtered. If they're not that's a bug.

**Comment by christopherhesse** [comment]
Looks like it's only filtered when using `FILTERED` actions https://github.com/openai/retro/blob/master/retro/retro_env.py#L167

**Comment by endrift** [comment]
`DISCRETE` is based off of `button_combos`, which is generated from a filtered set: https://github.com/openai/retro/blob/master/retro/retro_env.py#L94

**Comment by christopherhesse** [comment]
Hmm, so what should `env.action_space.n` be for this game? https://github.com/openai/retro/blob/master/retro/data/stable/Skiing-Atari2600/scenario.json#L21

**Comment by endrift** [comment]
9 (3 * 3)

**Comment by christopherhesse** [comment]
```
In [4]: env = retro.make('Skiing-Atari2600', use_restricted_actions=retro.Actions.DISCRETE)                                                                                    

In [5]: env.action_space.n                                                                                                                                                     
Out[5]: 18
```

**Comment by endrift** [comment]
I'll investigate next week.

**Comment by christopherhesse** [comment]
@endrift did you get a chance to look at this?

**Comment by endrift** [comment]
No, sorry. I'll see if I can find some time today or next week.

**Comment by christopherhesse** [comment]
Thanks!
