### ISSUE TITLE
Integration UI search does not work

### ISSUE THREAD

**Issue by tylerroost** [openai/retro#150]
As the title says when I try to search for a variable say HP in pokemon I start by searching for the current value say 20, then I get hit then search for the new value and there are 0 results and solutions would be greatly appreciated 

## System information

- Windows 10
- python 3.6
- Retro 0.6.0 and 0.7.0

**Comment by tylerroost** [comment]
I am starting to believe that this may only be for Gameboy games because search works fine for Gameboy Advanced games

**Comment by endrift** [comment]
Could be. I'll try to find some time to look into it this week.

**Comment by tylerroost** [comment]
Thank you

**Comment by endrift** [comment]
Please don't close this before I've had a chance to look at it.

**Comment by endrift** [comment]
Seems to work for me with latest build. For reference, according to Data Crystal the right address is D015 and type is >u2.
