### ISSUE TITLE
Reward always 0

### ISSUE THREAD

**Issue by jadeknightjr** [openai/retro#151]
## Issue summary

[So I saw two similar posts to this: https://github.com/openai/retro/issues/40, https://github.com/openai/retro/issues/72. However, the first link appears to be for the purpose of the contest, which I'm not trying to do (just playing around with retro). The second link uses WinPython which seems to be meant for windows... but I'm using a Mac.

Perhaps things have changed significantly since this tutorial (https://www.youtube.com/watch?v=S4jI-ambYKE) but for some reason my reward always seems to be 0. My reward is how far sonic can move to the right. In my practice file (/Users/dumpy/Documents/ML_FUN/retroAI/tut1.py), I have the following code, `import retro

env = retro.make("SonicTheHedgehog-Genesis", "GreenHillZone.Act1")
#env = retro.make("GoldenAxe-Genesis", "1Player.Arcade.DefaultCharacter.Level1")

env.reset()

done = False

while not done:
    env.render()

    #action = env.action_space.sample()
    action = [0,0,1,0,0,0,0,1,1,1,0,0]
    #print(action) # The 1/0s tell you whether or not a button on genesis is on/off

    ob, reward, done, info = env.step(action)       # ob = image of screen at time of action
    print("Action ", action, "Reward ", reward)     # rew = amount of reward that he earned from whatever in scenario file
                                                    # done = whether done condition met
                                                    # info = dict of all values set in data.json`

Meanwhile, in my scenario.json folder(/Users/dumbpy/Documents/ML_FUN/retroAI/gym-retro/retro/data/stable/SonicTheHedgehog-Genesis/scenario.json) I have the following, 

> {
  "done": {
    "variables": {
      "lives": {
        "op": "zero"
      }
    }
  },
  "reward": {
    "variables": {
      "x": {
        "reward": 1.0
      }
    }
  }
}

I've attached a small gif showing the reward stuck at 0.
![video](https://user-images.githubusercontent.com/29694852/54859885-d8818000-4ce8-11e9-8ec0-db3a236a3a0f.gif)

]

## System information

- [Mac Mojave 10.14.3]
- [Python 3.7.2]
- [Gym Retro v0.7.0]

**Comment by christopherhesse** [comment]
Your scenario file looks correct, if you just type a bunch of garbage in there does retro fail to start?  If not, you are probably not modifying the correct scenario.json, look for one under `retro.__path__`.  If retro does fail to start, you're editing the correct file. But I tried this and it worked fine:

```
{
  "done": {
    "variables": {
      "lives": {
        "op": "zero"
      }
    }
  },
  "reward": {
    "variables": {
      "x": {
        "reward": 1.0
      }
    }
  }
}
```

You can also try `scenario='contest'` which will use the contest scenario based on x-position.

**Comment by jadeknightjr** [comment]
I did what you first advised with writing garbage. Writing garbage did not seem to work as it still ran with reward being 0.

I then tried to find the scenario.json which was under `retro.__path__` which I could not find both on my computer and on Github's search for openai/retro. Can you clarify what `retro.__path__` may be referring to? 

I did notice a second scenario.json file at this location.

`/Users/dumby/Documents/ML_FUN/retroAI/lib/python3.7/site-packages/retro/data/stable/SonicTheHedgehog3-Genesis/scenario.json`

Which look like this after swapping score for x:
> {
  "crop": [
    0,
    0,
    0,
    0
  ],
  "done": {
    "variables": {
      "lives": {
        "op": "zero"
      }
    }
  },
  "reward": {
    "variables": {
      "x": {
        "reward": 1.0
      }
    }
  }
}
However, even when making this file just filled with random text would still run with reward being 0.

Perhaps this may be due to the way I started my environment?
as I did the following steps in order... 
**mkdir retroAI**
**python3 -m vena retroAI** 
**cd retroAI**
**git clone https://github.com/openai/retro.git gymretro**
 **pip3 install gym-retro**

**Comment by jadeknightjr** [comment]
OK I think I got it fixed somehow... editing this scenario.json `/Users/dumbpy/Documents/ML_FUN/retroAI/lib/python3.7/site-packages/retro/data/stable/SonicTheHedgehog-Genesis/scenario.json`
would work only after I restarted my terminal for some reason. I'm guessing that perhaps when you create an environment to run retro, it causes it to look at a different scenario.json file?

**Comment by christopherhesse** [comment]
I doubt you have to restart your terminal, but you probably have to restart python.
