### ISSUE TITLE
how to get SonicTheHedgehog-Genesis rom.md?

### ISSUE THREAD

**Issue by DenShlk** [openai/retro#171]
## Issue summary

I want to train ai to play Sonic, but can't run game...
I can play Airstriker-Genesis, because it contains rom.md
I try find rom.md for sonic [here](https://www.freeroms.com/rom/genesis/sonic_the_hedgehog.htm), [here](https://coolrom.com.au/roms/genesis/1283/Sonic_the_Hedgehog.php) but when I run game with loaded files I see blue window:(

## System information

- Win10
- 3.7
- 0.7.0

**Comment by 8bitmp3** [comment]
Here are two ways to get it to work with Retro Gym https://github.com/openai/retro, both of which involve getting the game from [Steam](https://store.steampowered.com/app/71113/Sonic_The_Hedgehog/) - yes, it does cost $ but it's sometimes on sale, sometimes as part of a bundle with Sonic 2 and Sonic 3 & Knuckles. 

1) Follow the unofficial instructions by @shun1024 - see https://github.com/openai/retro/issues/35 (OpenAI's @christopherhesse closed it and it seems to work for some folks). It may work with Windows.
> 1. pip install gym-retro
> 2. create a steam account and buy the following game
> https://store.steampowered.com/app/71113/Sonic_The_Hedgehog/
> 3. python -m retro.import.sega_classics (this is to install the purchased games)
> 4. test with: https://contest.openai.com/details

or

2) Follow official instructions and get Sonic The Hedgehog from Steam. Download it. Then follow OpenAI's Retro Contest [quickstart guide](https://contest.openai.com/2018-1/details/).

> If you already have the games installed, you can import them directly:
> ```py
> python -m retro.import <path to steam folder>
> ```
> To install the repo for the contest, which includes environment wrappers to set things up in the official way, run this:
> ```
> git clone --recursive https://github.com/openai/retro-contest.git
> pip install -e "retro-contest/support[docker,rest]"
> ```

**Comment by christopherhesse** [comment]
Thanks for answering @8bitmp3!
