### ISSUE TITLE
Emulator Performance

### ISSUE THREAD

**Issue by christopherhesse** [openai/retro#172]
It looks like inlining a method and creating some constants improves speed dramatically on ALE: https://github.com/mgbellemare/Arcade-Learning-Environment/pull/265

It's possible there are similar simple changes that could be made to other emulators.

**Comment by endrift** [comment]
Most of the other emulators have already had deep amounts of optimization already worked on, so Stella may be the odd one out here, not the average case.

**Comment by mgbellemare** [comment]
As FYI, Xitari (https://github.com/deepmind/xitari) is sped up about 100% relative to ALE, although it also stripped some actual functionality in the process...

**Comment by endrift** [comment]
Writing new libretro bindings for ALE's Stella might be a better idea than speeding up the newer version of Stella.

**Comment by christopherhesse** [comment]
Going to close this in favor of https://github.com/openai/retro/issues/127 since it sounds like most cores are already optimized a decent amount.

**Comment by christopherhesse** [comment]
Although with some fancy customizations, it's likely we still could improve performance of the emulators since we care more about speed than accuracy.
