### ISSUE TITLE
sound support

### ISSUE THREAD

**Issue by MatPoliquin** [openai/retro#173]
Is there any plan to get sound support for playback and eventually training?

**Comment by christopherhesse** [comment]
I think sound support already works for playback, it would be nice to have sound as a supported `obs_type` here: https://github.com/openai/retro/blob/master/retro/retro_env.py#L27 (as well as supporting multiple `obs_type`s in a dictionary observation space).

I would consider a PR that added this.  It looks like you can already access sound data here: https://github.com/openai/retro/blob/master/retro/scripts/playback_movie.py#L138

**Comment by MatPoliquin** [comment]
Thanks for the info, I managed to add sound support in baselines when using the save_video_interval/save_video_length, might submit a Pull Request later if I find a way to make it cleaner
