### ISSUE TITLE
Potential support for red alert?

### ISSUE THREAD

**Issue by YuansongFeng** [openai/retro#174]
How likely is it in the future to add the support for large-scale real time strategy game like Red Alert? Training games like these probably requires tons of compute and time, but it would be really exciting if Retro could initiate such an attempt. Would definitely love to help if there's a possibility.

**Comment by christopherhesse** [comment]
It looks like there is a version for PS1, so it's likely possible, someone already tried to integrate a PS libretro core here: https://github.com/openai/retro/issues/169

One of the bigger problems though is that training on pixels could be hard, and that I think that training on these sorts of games is often done via self-play which is unlikely to work with the libretro setup.

**Comment by christopherhesse** [comment]
Closing this since we're unlikely to add support for this particular game.  You're welcome to fork the project to add that game though.  We could potentially add support for a new core in the main release but it should likely be tested out in a fork first.
