### ISSUE TITLE
Intense flickering of UI in retro integration tool

### ISSUE THREAD

**Issue by MatPoliquin** [openai/retro#175]
When you load a rom in the integration tool, the UI starts to flicker.

I generated a gif where I repro the bug:
![bug](https://user-images.githubusercontent.com/7024551/62364092-41a8b800-b553-11e9-9aff-add90582576c.gif)

note: it flickers only when the game is running, not when paused 

## System information
Ubuntu 18.10
Python 3.6
gym-retro 0.7.0

**Comment by MatPoliquin** [comment]
I did some debugging and I find that it's the calls in 
`void EmulatorController::runOneStep() function - EmulatorController.cpp`
When I comment out
`emit dataUpdated();`
The UI flickers much less
and when I comment out along with emit dataUpdated()
`m_re.run();`
The flickering stops completly

dataUpdated() does this
`void EmulatorController::dataUpdated()
{
    QMetaObject::activate(this, &staticMetaObject, 3, nullptr);
}`

I am not an expert in the QT framework but this seems like a heavy way to refresh the UI

**Comment by christopherhesse** [comment]
Thanks for the bug report!

This sounds most likely to me to be a bug in how we are using Qt for the UI or a bug using Qt on this particular ubuntu.

**Comment by christopherhesse** [comment]
I may be able to try this out in a VM later, but can you verify that you're using the latest Qt and latest nvidia drivers if you have an nvidia card?

**Comment by MatPoliquin** [comment]
Yep, I have latest for both. The problem also happens on my other setups

**Comment by MatPoliquin** [comment]
As a temporary workaround, I just tried with the Nouveau display drivers and the flickering goes away but I lose CUDA support

![Screenshot from 2019-08-05 07-46-46](https://user-images.githubusercontent.com/7024551/62430912-345b1b80-b755-11e9-8272-a2663448a41b.png)

**Comment by christopherhesse** [comment]
Good to know, even if I got an ubuntu VM working, I might have trouble reproducing this issue.

**Comment by christopherhesse** [comment]
I got the VM working, but I'm going to guess it uses the nouveau driver or some mesa thing.  So there's some problem that only appears with nvidia drivers.  Does the flickering happen if you load `Airstriker-Genesis`?  If you only remove `m_re.run()` does that have any effect without the `dataUpdated()` change?

**Comment by endrift** [comment]
The VM does not have direct access to any Nvidia graphics card most likely, so it'll just be Mesa, and probably software rasterized.

**Comment by MatPoliquin** [comment]
@christopherhesse  If I remove m_re.run() it flickers a bit less

In the meantime I tried on a RX 580 (with same OS/Software config) and it doesn't flicker.
I also tried forcing XWindows to only use the Intel integrated Graphics chip ( while tensorflow still uses the NVIDIA gpu) and it stopped flickering.

So basically the problem seems only to be happening with NVIDIA drivers, at least on these two cards:
- Geforce MX 150 (laptop GPU)
- GTX 1060

**Comment by christopherhesse** [comment]
Good to know, this may be a bug in Qt or in the nvidia drivers.  In those two cases it's unlikely to be a retro bug, so I'm going to close this for now.  Thanks for providing the workaround!

**Comment by MatPoliquin** [comment]
I know it's late but I found a fix for this bug:
in main.cpp, line 28:
Instead of SingleBuffer, it should be:
`format.setSwapBehavior(QSurfaceFormat::DoubleBuffer);`

After this fix I experience no more flickering. I know you don't accept any new PR so I made this fix in my own fork:
https://github.com/MatPoliquin/stable-retro
