### ISSUE TITLE
Bug on converting actions to array

### ISSUE THREAD

**Issue by jdiazgon** [openai/retro#177]
## Issue summary

I have integrated Mario Kart Super circuit (GameBoy Advanced) into the Retro enviroment. I have been able to create a `scenario.json` and a state file. I also tried your examples like `random_agent.py` and they work perfectly fine, I can visualize the game and the agent randomly selects actions. When I print the actions I see that they are an array of 12 binary values, for instance:

- [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] = No button is pressed
- [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]= Slowly accelerate
- [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0] = Accelerate
- [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1] = Jump
- [0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0] = Accelerate and turn right

The problem arises when trying to use neural networks and reinforcement learning. The following method inside your [retro_env.py](https://github.com/openai/retro/blob/master/retro/retro_env.py#L164) file returns an error `invalid index to scalar variable`:
```Python
ap = a[self.num_buttons * p:self.num_buttons * (p + 1)]
```
Variable `a` should be an array of actions (I guess similar to what I've shown above) but it actually is a scalar that goes on the range 1-12, just like my array size. This completely breaks the code.

In order to fix this issue I have implemented a workaround:

```Python
            else:
                # My workaround start
                if type(a) is np.int32 or type(a) is np.int64:
                    tmp = [0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0] 
                    tmp[a] = 1
                    a = tmp
                # My workaround end
                ap = a[self.num_buttons * p:self.num_buttons * (p + 1)]
                for i in range(len(ap)):
                    action |= int(ap[i]) << i
                if self.use_restricted_actions == retro.Actions.FILTERED:
                    action = self.data.filter_action(action)
            ap = np.zeros([self.num_buttons], np.uint8)
            for i in range(self.num_buttons):
                ap[i] = (action >> i) & 1
            actions.append(ap)
```
What I'm doing is forcing the agent to accelerate and also set a `1` into the index that `a` returns. This doesn't throw any error but I would like to know if I'm doing something wrong or if this is a bug. I'm afraid that my workaround will worsen my reinforcement learning approach.

Now I'm going to paste the code that I use in order to configure the environment, maybe you find a mistake:
```Python
(...)
env = retro.make(args.game, args.state or retro.State.DEFAULT, scenario=args.scenario, record=args.record, players=args.players, obs_type=obs_type)
actions_count = env.action_space

# I set my neural network
model = Sequential()
(...)
memory = SequentialMemory(limit=100, window_length=1)

policy = LinearAnnealedPolicy(EpsGreedyQPolicy(), attr='eps',
                              value_max=1, value_min=.01, value_test=.05, nb_steps=nb_steps)

dqn = DQNAgent(model=model, nb_actions=actions_count.n, memory=memory, nb_steps_warmup=1000,
               target_model_update=10000, policy=policy)

dqn.compile(Adam(lr=.00025), metrics=['mae'])

# Training execution
dqn.fit(env, nb_steps=nb_steps, visualize=True, verbose=1)
```
Thanks in advance for your help.

## System information

- Windows 10
- Python 3.7.3
- Gym retro 0.7.0

**Comment by jdiazgon** [comment]
By the way, I have already tried the latest changes on version 0.7.1 and that doesn't fix my issue.

**Comment by endrift** [comment]
`a` is a user provided value. Make sure use_restricted_actions is set to retro.Actions.DISCRETE when making the environment. AFAIK, DQN requires this.

**Comment by christopherhesse** [comment]
I believe @endrift has the correct solution, the RL code you are using likely expects a discrete action space and it should be throwing an exception when you give it an environment with a mismatched space.

Alternatively there could be better checks in retro for invalid input, but then you might want to disable the checks to avoid performance issues, so requiring that users send in actions that match `env.action_space` may be reasonable.

If you use the discrete space, but it's got too many actions, check out this example `Discretizer` wrapper: https://github.com/openai/retro/blob/master/retro/examples/discretizer.py to reduce the number of discrete actions (as an alternative to `retro.Actions.Discrete`)

Please file a new issue or re-open if this doesn't solve your problem.

**Comment by jdiazgon** [comment]
> Make sure use_restricted_actions is set to retro.Actions.DISCRETE when making the environment.

Thanks! That worked:

```Python
env = retro.make(args.game, args.state or retro.State.DEFAULT, use_restricted_actions=retro.Actions.DISCRETE, scenario=args.scenario, record=args.record, players=args.players, obs_type=obs_type)
```
> If you use the discrete space, but it's got too many actions, check out this example Discretizer wrapper

That will be also helpful :)
