### ISSUE TITLE
Start a new game in PongAtari-2600

### ISSUE THREAD

**Issue by nfkok** [openai/retro#183]
## Issue summary
I want to play the pong game against RL in the Pong environment.
I tried to map the keys from keyboard to action space, I figured out that action space which controls player 1 is indices 0,1,2,3,4,5 where up is 4, down is 5; whereas 6,7,8,9,10,11 are for player 2 where up is 6, down is 7.
So I set the action space for example 'up' for both player 1 and player 2 as [0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0]
When I start to play the game, after a game is over, I could not proceed to next game.
Although the score board show 0:1, the rewards, obs, done and info(score 1 and score 2) are all 0 (false for done).
Then I flip the first bit of the action space, it turns out to be when player 1 wins, i can proceed to next game, but when player 2 wins, it stuck and could not proceed.

My python coding segment in main loop is as follow is as follow (which could not proceed to new game after the first game):

` 
while True:

	
	if obs is not None:
		rendered=env.render(mode='rgb_array')
		display_arr(screen,rendered,transpose=transpose,video_size=video_size)

	for event in pygame.event.get():
		if event.type==pygame.KEYDOWN:
			if event.key==K_UP:
				human_action=6
			elif event.key==K_DOWN:
				human_action=7
		elif event.type==pygame.KEYUP:
			if event.key==K_UP:
				human_action=6
			elif event.key==K_DOWN:
				human_action=7
	cur_x = prepro(obs)
	x = cur_x - prev_x if prev_x is not None else np.zeros(D)
	prev_x = cur_x
	action=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
	aprob, h = policy_forward(x)
	rl_action = 4 if np.random.uniform() < aprob else 5

	action[rl_action],action[human_action]=1,1
  
	obs, reward, done, info = env.step(action)
	
	
	if done:
		obs=env.reset()
		prev_x=None

	pygame.display.flip()
	clock.tick(fps)
  `

So what changes should I make to the action space?
Thank you

## System information

- [Operating system]
- [Python version]
- [Gym Retro version]

**Comment by christopherhesse** [comment]
I tested each of the 16 actions, it looks like actions 15 and 16 (index 14 and 15) restart the game, depending on who won.  I think it's meant to be that the player that last scored is "serving" the ball to the other player.

**Comment by nfkok** [comment]
Thanks.
I tried to set if-else statements inside the loop to see if player 1 or player 2 scores to toggle actions 15 and 16, but somehow it makes the paddle movements of both players to be lagging. Any suggestions on how should I implement the serving each time a player scores?

**Comment by christopherhesse** [comment]
What if you wait 3 seconds after a point is scored, then hit both buttons?

**Comment by nfkok** [comment]
Thanks, I have done it. After each game, I sleep for 1 sec, and read player keyboard input to serve the ball.
