### ISSUE TITLE
failled to install gym-retro on windows

### ISSUE THREAD

**Issue by ChenSun-YP** [openai/retro#185]
## unable to install gymretro

I have tried to install the repo by:
pip3 install gym-retro;
pip install gym-retro;
python setup.py install;
as well as the methon on https://retro.readthedocs.io/en/latest/developing.html#development.
And similar error pops out.

## System information
Command "C:\Users\Administrator\PycharmProjects\as\venv\Scripts\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\Administrator\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" develop --no-deps" failed with error code 1 in C:\Users\Administrator\gym-retro\
- windows 10
- python 3.7
- [Gym Retro version]

**Comment by christopherhesse** [comment]
Could you paste the entire error you get when doing `pip3 install gym-retro`?

**Comment by ChenSun-YP** [comment]
Thank you for concerning， but I have successfully installed gym retro by changing my python version to 3.6 64bit.
Thanks again.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________
