### ISSUE TITLE
Pong using RAM

### ISSUE THREAD

**Issue by nfkok** [openai/retro#186]
## Issue summary

How can I set the observation to be RAM instead of RGB array?

I tried as follow but the observation is still in RGB.

env=retro.make(game="Pong-Atari2600", players=1)
retro.Observations(1)
obs=env.reset()

## System information

- [Operating system]
- [Python version]
- [Gym Retro version]

**Comment by christopherhesse** [comment]
You need to set the observations flag: https://retro.readthedocs.io/en/latest/python.html#observations

```
import retro
env = retro.make(game="Pong-Atari2600", obs_type=retro.Observations.RAM)
```
