### ISSUE TITLE
Unable to cite gym retro

### ISSUE THREAD

**Issue by BlkPingu** [openai/retro#189]
## Issue summary

I retro for my research and now I would like to cite it. However I can't find a DOI or any trace that this has been made available.
Please fix this.
https://guides.github.com/activities/citable-code/

**Comment by christopherhesse** [comment]
I've added a citation link at the bottom of the README: https://github.com/openai/retro#citation

Thanks for bringing this up!

**Comment by BlkPingu** [comment]
Thank you for updating the readme, but you have added bibtex for the the paper, related to the repo, not a release of the repo. The former is helpful when searching for your research that led to the code, but I require the latter: a citable release. It's all laid out for you in this article: https://guides.github.com/activities/citable-code/

**Comment by christopherhesse** [comment]
I see, how is this better than citing the specific pip version or git commit hash of the gym retro version you are using for an experiment?
