### ISSUE TITLE
2 Player Games

### ISSUE THREAD

**Issue by ma-rv** [openai/retro#192]
Hey, which games despite Pong support the 2 player mode? Couldn't find any information in the documentation. Thank you!

**Comment by christopher-hesse** [comment]
It looks like it's just Pong-Atari2600 and FishingDerby-Atari2600 that have a 2 player state already.  It's likely that other game support 2 player (such as sonic the hedgehog).  You'll probably want to copy and paste the existing integration for such a game and then add the 2 player state.   Sorry about the lack of documentation!
