### ISSUE TITLE
AttributeError: module 'pyglet.window' has no attribute 'get_platform'

### ISSUE THREAD

**Issue by fsimond** [openai/retro#193]
## Issue summary
This command crashes:
> python -m retro.examples.interactive --game Airstriker-Genesis
With error:
> AttributeError: module 'pyglet.window' has no attribute 'get_platform'

More details:
$ pip install gym-retro
Collecting gym-retro
  Downloading gym_retro-0.7.0-cp37-cp37m-macosx_10_7_x86_64.whl (146.0 MB)
     |████████████████████████████████| 146.0 MB 18.4 MB/s
Collecting pyglet==1.*,>=1.3.2
  Downloading pyglet-1.4.10-py2.py3-none-any.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 4.8 MB/s
Collecting gym
  Downloading gym-0.16.0.tar.gz (1.6 MB)
     |████████████████████████████████| 1.6 MB 15.1 MB/s
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Collecting scipy
  Downloading scipy-1.4.1-cp37-cp37m-macosx_10_6_intel.whl (28.4 MB)
     |████████████████████████████████| 28.4 MB 6.2 MB/s
Collecting numpy>=1.10.4
  Downloading numpy-1.18.1-cp37-cp37m-macosx_10_9_x86_64.whl (15.1 MB)
     |████████████████████████████████| 15.1 MB 23.7 MB/s
Collecting six
  Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)
Collecting cloudpickle~=1.2.0
  Downloading cloudpickle-1.2.2-py2.py3-none-any.whl (25 kB)
Building wheels for collected packages: gym, future
  Building wheel for gym (setup.py) ... done
  Created wheel for gym: filename=gym-0.16.0-py3-none-any.whl size=1648670 sha256=0248463d86f6b7d70c0cb636031303a2ff3bc0a9a83e9ae9901b1f188e626d03
  Stored in directory: /Users/florians/Library/Caches/pip/wheels/eb/89/f3/c073e53d947fd5d420d799c854b35019265ad865031323c867
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=07b70091d2cc60d39c306ac81b42a34af2cc7c3d22ffff6027babcba1f7d619a
  Stored in directory: /Users/florians/Library/Caches/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0
Successfully built gym future
Installing collected packages: future, pyglet, numpy, scipy, six, cloudpickle, gym, gym-retro
Successfully installed cloudpickle-1.2.2 future-0.18.2 gym-0.16.0 gym-retro-0.7.0 numpy-1.18.1 pyglet-1.4.10 scipy-1.4.1 six-1.14.0
(datathon)  ~  python -m retro.examples.interactive --game Airstriker-Genesis
Traceback (most recent call last):
  File "/Users/florians/miniconda3/envs/datathon/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/florians/miniconda3/envs/datathon/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/florians/miniconda3/envs/datathon/lib/python3.7/site-packages/retro/examples/interactive.py", line 250, in <module>
    main()
  File "/Users/florians/miniconda3/envs/datathon/lib/python3.7/site-packages/retro/examples/interactive.py", line 245, in main
    ia = RetroInteractive(game=args.game, state=args.state, scenario=args.scenario)
  File "/Users/florians/miniconda3/envs/datathon/lib/python3.7/site-packages/retro/examples/interactive.py", line 204, in __init__
    super().__init__(env=env, sync=False, tps=60, aspect_ratio=4/3)
  File "/Users/florians/miniconda3/envs/datathon/lib/python3.7/site-packages/retro/examples/interactive.py", line 34, in __init__
    platform = pyglet.window.get_platform()
AttributeError: module 'pyglet.window' has no attribute 'get_platform'

## System information

- macOS Catalina
- Python 3.7.6
- 0.7.0

**Comment by christopherhesse** [comment]
Fixed by #195
