### ISSUE TITLE
release v0.7.1

### ISSUE THREAD

**Issue by christopherhesse** [openai/retro#196]
It's been awhile since the 0.7.0 release and it would be nice to publish the bug fixes.  It looks like this involves copying the generated wheel files and using twine.

**Comment by christopherhesse** [comment]
I'll likely do it tomorrow, sorry for the delay.

**Comment by christopherhesse** [comment]
Unfortunately this release is blocked by a build error on travis: https://travis-ci.org/openai/retro/jobs/656484775#L292

This is especially odd because as far as I can tell nothing has changed.  @endrift any ideas what could cause this?  I tried disabling parallel make in case it was some race condition, but it seems to happen reliably.

**Comment by christopherhesse** [comment]
@justinkterry I'm afraid you will have to install from source for now

**Comment by endrift** [comment]
@christopherhesse try deleting the build cache for Python 3.7/Windows 64. Looks like an empty .o file wound up in the cache.

Also now is a good time to add Python 3.8 wheels

**Comment by christopherhesse** [comment]
Oh good call, thanks!

**Comment by christopherhesse** [comment]
Uploaded the new wheels and made an issue for python 3.8
