### ISSUE TITLE
Pong Multiplayer Actions

### ISSUE THREAD

**Issue by jiaj15** [openai/retro#198]
## Issue summary
I try to use the 2-player Atari Pong 2600 for testing my RL agent. It's quite confusing in figuring out the action meaning and definition of player2. The game gets stuck at some time point and there is no ball served.
[Put a detailed description of the issue here.]
I discretized the action space for the first time using a method like SonicDiscretizer through providing combinations of buttons such as 'BUTTON', 'UP', 'DOWN'. I tried to use keyboard to figure out which button serves the ball for player 2. But none of them works.
```python
class Discretizer(gym.ActionWrapper):
    """
    Wrap a gym environment and make it use discrete actions.
    Args:
        combos: ordered list of lists of valid button combinations
    """

    def __init__(self, env, combos):
        super().__init__(env)
        assert isinstance(env.action_space, gym.spaces.MultiBinary)
        buttons = env.unwrapped.buttons
        self._decode_discrete_action = []
        print(buttons)
        buttons = []
        buttons.append(['BUTTON', None, 'SELECT', 'RESET', 'UP', 'DOWN', 'LEFT', 'RIGHT']) 
        buttons.append(['UP', 'DOWN',  'LEFT', 'RIGHT', 'BUTTON', None,'SELECT', 'RESET']) # I could only make sure that the 7th and 8th digit is UP and DOWN for player2.

        for combo in combos:
            arr = np.array([False] * env.action_space.n)
            for i,button_two in enumerate(combo):
                if len(button_two)==0:
                    arr[6*i + buttons[i].index(None)] = True

                for button in button_two:
                    arr[6*i+ buttons[i].index(button)] = True
            self._decode_discrete_action.append(arr.copy())
            print((combo, arr, len(self._decode_discrete_action)))
        self.action_space = gym.spaces.Discrete(len(self._decode_discrete_action))

    def action(self, act):
        return self._decode_discrete_action[act].copy()


class PongDiscretizer(Discretizer):
    """
    Use Sonic-specific discrete actions
    based on https://github.com/openai/retro-baselines/blob/master/agents/sonic_util.py
    """
    def __init__(self, env, players=2):
        lens1 = [[], ['BUTTON'], ['UP'], ['DOWN'], ['BUTTON','UP'], ['BUTTON','DOWN']]
        # lens2 = [[], ['BUTTON'], ['UP'], ['DOWN'], ['BUTTON','UP'], ['BUTTON','DOWN']]
        lens2 = [[], ['BUTTON'], ['UP'], ['DOWN'], ['RESET'], ['SELECT'], ['LEFT'], ['RIGHT']]
        combos = []
        for i in range(6):
            for j in range(6):
                combos.append((lens1[i], lens2[j]))           
        super().__init__(env=env, combos=combos)

```

## System information

- [Operating system]
- [Python version]
- [Gym Retro version]

**Comment by jiaj15** [comment]
I found it! The representation of 16-byte action space is 
Player 1 : 0: 'BUTTON',  4: 'UP', 5: 'DOWN'
Player 2 : 6: 'UP', 7: 'DOWN', 15: 'BUTTON'

'BUTTON' means to fire the ball

**Comment by AleGaglio** [comment]
Forgive me @jiaj15 . I don't understand how to solve this issue. 
if I modify the code in
`
...
buttons.append(['BUTTON', None, 'SELECT', 'RESET', 'UP', 'DOWN', 'UP', 'DOWN']) 
buttons.append(['UP', 'DOWN',  'LEFT', 'RIGHT', 'BUTTON', None,'SELECT', 'BUTTON'])
...
`
The game continues to hang at some point and the ball is not served.

**Comment by jiaj15** [comment]
I am not sure why but it works if I keep repeating the action "BUTTON" for several steps.  For example, if one of the agent scores, we know someone should serve the ball so I can just append "BUTTON" to the original action.
