### ISSUE TITLE
Broken pipe trying to run the PPO example 

### ISSUE THREAD

**Issue by Yousef-D** [openai/retro#202]
So I tried running
python -m retro.examples.ppo --game Airstriker-Genesis, and it gave me a broken pipe. What can I do to fix this?
found here: https://retro.readthedocs.io/en/latest/getting_started.html
![image](https://user-images.githubusercontent.com/58224678/79076627-85171100-7cf3-11ea-998d-b6484b6c5518.png)

System information

- Operating system: windows 
- Python version :3.7
- Gym Retro version: 0.7

**Comment by christopherhesse** [comment]
What version of tensorflow do you have installed?  The docs for baselines say you need 1.4 to 1.14: https://github.com/openai/baselines#tensorflow-versions

**Comment by Yousef-D** [comment]
I see, thanks for the help man
