### ISSUE TITLE
Find the contest details really confusing and unhelpful? Read here for beginners FAQ

### ISSUE THREAD

**Issue by HanSeoulOh** [openai/retro#21]
Noticed that the official contest support is severely understaffed and thus unresponsive when it comes to technical support, so I've compiled a couple pointers to help people get started. I will update this as I progress. Feel free to add any common issues and resolutions that you have noticed as well.

# FAQ #

### Q1. Do I need to pay for the sonic games? ###
A1. Yes, using other ROMs not from steam have not worked for me personally.

### Q2. Can't install sonic on my mac/linux ###
A2. I got them by using Windows, another contestant mentioned using wine with linux; Installing Steam and copying the roms from there.

### Q3. Script ```python -m retro.import.sega_classics``` to import ROMs doesn't work ###
A3. Try moving ROMs from your steam folder to your working folder, then ```python -m retro.import .```

### Q4. Docker doesn't install for Windows because you don't have Pro. ###
A4. Use [Docker Toolbox](https://docs.docker.com/toolbox/toolbox_install_windows/#how-to-uninstall-toolbox)

### Q5. CPU-Tensorflow gives me a warning message: ```tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use ... instructions, but these are available on your machine and could speed up CPU computations.``` ###

A5. Don't fear, this isn't too hard to resolve. Give this a read: https://gist.github.com/venik/9ba962c8b301b0e21f99884cbd35082f and here https://www.tensorflow.org/install/install_sources

### Q6. Don't have GPU and getting ```ImportError: libcuda.so.1: cannot open shared object file: No such file or directory```

A6. You need to use docker to build two different images, one for testing locally and one for submitting. Will add details after I figure out how to do this...

### Q7. Can I submit a job through Docker CLI instead of the contest webpage ###

A7. Guide given by @endrift 
```retro-contest login --server https://contest.openai.com  && retro-contest job submit -t $TAG_NAME ``` will automatically tag $TAG_NAME as $REGISTRY_NAME/$TAG_NAME, push, and start the job note that it pulls down $REGISTRY_NAME for you so it doesn't need to be set locally

**Comment by brandonraphael** [comment]
Really great help, thanks for this.

**Comment by unixpickle** [comment]
Now that the [contest is completed](https://blog.openai.com/first-retro-contest-retrospective/), may we close this issue?
