### ISSUE TITLE
v0.8.0 build fails on windows: "ld returned 1 exit status"

### ISSUE THREAD

**Issue by ObiDriftKenobi** [openai/retro#226]
## Issue summary

Good evening (or morning, depends where you live). I tried building this library from source after a friend told me the pypi versions are hacked and contain viruses. (I don't really believe that, but I wanted to be safe). I followed the build steps, installed msys2 64, git, cmake, and then gcc with pacman. Near the end (crash) of the build, it spits out a bunch of "multiple definition" errors and ultimately stops with "ld returned 1 exit status". Being a dummy around C, I didn't understand much. Am I doing something wrong?

## System information

- [Operating system] Windows 10
- [Python version] 3.8.7
- [Gym Retro version] 0.8.0

Full error attached.
[log.txt](https://github.com/openai/retro/files/5793276/log.txt)

**Comment by endrift** [comment]
You'll need to apply #213 manually. It's already been fixed in master, but your local version is I guess older than master. Check the "changes" section to see what changes need to be made.

**Comment by ObiDriftKenobi** [comment]
Thanks, that helped... to advance. Now, the build fails at this, and I'm unsure whether my compiler is having a stroke or not.

```
[ 95%] Building CXX object CMakeFiles/retro-base.dir/src/movie-bk2.cpp.obj



cccccc111pppllluusus.s.e.exexex:ee ::o uotu t o oufo
fctc   1mmoepefmlmuo osrmr.yeye m oaxarlely:ll  ooaolucclt aoaotctfiai ntnmgigne g m6o65 r558y 36a l5b3l7y6o1t c3a6bet8ysi t
nbegys t
6e5s5
36 bytes
make[3]: *** [CMakeFiles/retro-base.dir/build.make:101: CMakeFiles/retro-base.dir/src/data.cpp.obj] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [CMakeFiles/retro-base.dir/build.make:171: CMakeFiles/retro-base.dir/src/movie-bk2.cpp.obj] Error 1
make[3]: *** [CMakeFiles/retro-base.dir/build.make:157: CMakeFiles/retro-base.dir/src/movie.cpp.obj] Error 1
make[3]: *** [CMakeFiles/retro-base.dir/build.make:87: CMakeFiles/retro-base.dir/src/coreinfo.cpp.obj] Error 1
make[2]: *** [CMakeFiles/Makefile2:961: CMakeFiles/retro-base.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:996: CMakeFiles/retro.dir/rule] Error 2
```
I am not even joking. That's exactly what went out of it. I didn't write that gibberish above.

...perhaps my computer is telling me to quit programming.
