### ISSUE TITLE
Can't download Integration UI Packages

### ISSUE THREAD

**Issue by TiddlyWiddly** [openai/retro#241]
## Issue summary

When I try to download the Integration UI Package for Windows or Mac here (https://retro.readthedocs.io/en/latest/integration.html#the-integration-ui) I get a NoSuchBucket error. How do I download the package or install it?

## System information

- [Operating system]
- [Python version]
- [Gym Retro version]

**Comment by onaclov2000** [comment]
I too am interested in this, I havent found it yet myself

**Comment by nathanrhart** [comment]
Hi, I previously raised this, links can be found here:
https://github.com/openai/retro/releases/tag/f347d7e
Hope this helps.

**Comment by TiddlyWiddly** [comment]
Thanks.
