### ISSUE TITLE
Installation Failed 

### ISSUE THREAD

**Issue by joneswong** [openai/retro#25]
## Issue summary

Got the failure information when executing `pip install -e .`

In file included from /gruntdata/app_data/jones.wz/rl/gym-retro/src/coreinfo.cpp:1:0:
    /gruntdata/app_data/jones.wz/rl/gym-retro/third-party/json.hpp:67:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-comp
ilers"
             #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
              ^

Could you give me some help so that I can participate the competition involving Gym-retro?

## System information

- Linux (CentOS)
- GCC 5.4
- Python 3.6
- Latest Gym retro source code

**Comment by endrift** [comment]
This error shouldn't happen with gcc 5, only with < 4.9. Are you sure it detected the right version of GCC?

**Comment by endrift** [comment]
Is this still a problem?

**Comment by joneswong** [comment]
forgot to update this thread. I can use gym-retro now but I don't remember how to solve the problem...
