### ISSUE TITLE
sudo pip3 install -e . fail 

### ISSUE THREAD

**Issue by iamavieira** [openai/retro#28]
## Issue summary

sudo pip3 install -e . fail with output:
Obtaining file:///home/Dev/personal_projects/openAI_sonicthehedgehog/gym-retro
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.python.org/simple/setuptools_scm/: [Errno -2] Name or service not known -- Some packages may not be found!
    Download error on https://pypi.python.org/simple/setuptools-scm/: [Errno -2] Name or service not known -- Some packages may not be found!
    Couldn't find index page for 'setuptools_scm' (maybe misspelled?)
    Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
    No local packages or download links found for setuptools_scm
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/Dev/personal_projects/openAI_sonicthehedgehog/gym-retro/setup.py", line 67, in <module>
        use_scm_version=use_scm_version
      File "/usr/lib/python3.5/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1092, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1104, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 380, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 657, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('setuptools_scm')

## Setup.py

from setuptools import setup, Extension
from setuptools.command.build_ext import build_ext
import subprocess
import sys
import os
import shutil

VERSION_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'VERSION')

if not os.path.exists(os.path.join(os.path.dirname(__file__), '.git')):
    use_scm_version = False
    shutil.copy('VERSION', 'retro/VERSION.txt')
else:
    def version_scheme(version):
        with open(VERSION_PATH) as v:
            version_file = v.read()
        if version.distance:
            version_file += '.dev%d' % version.distance
        return version_file

    def local_scheme(version):
        v = ''
        if version.distance:
            v = '+' + version.node
        return v
    use_scm_version = {'write_to': 'retro/VERSION.txt',
                       'version_scheme': version_scheme,
                       'local_scheme': local_scheme}

class CMakeBuild(build_ext):
    def run(self):
        suffix = super(CMakeBuild, self).get_ext_filename('')
        pyext_suffix = '-DPYEXT_SUFFIX:STRING=%s' % suffix
        pylib_dir = ''
        if not self.inplace:
            pylib_dir = '-DPYLIB_DIRECTORY:PATH=%s' % self.build_lib
        python_executable = '-DPYTHON_EXECUTABLE:STRING=%s' % sys.executable
        subprocess.check_call(['cmake', '.', '-G', 'Unix Makefiles', pyext_suffix, pylib_dir, python_executable])
        if self.parallel:
            jobs = ['-j%d' % self.parallel]
        else:
            import multiprocessing
            jobs = ['-j%d' % multiprocessing.cpu_count()]
        subprocess.check_call(['make'] + jobs + ['retro'])

setup(
    name='gym-retro',
    author='OpenAI',
    author_email='vickipfau@openai.com',
    url='https://github.com/openai/retro',
    version=open(VERSION_PATH, 'r').read(),
    license='MIT',
    install_requires=['gym'],
    ext_modules=[Extension('retro._retro', ['CMakeLists.txt', 'src/*.cpp'])],
    cmdclass={'build_ext': CMakeBuild},
    packages=['retro', 'retro.data', 'retro.scripts', 'retro.import'],
    package_data={
        'retro': ['cores.json', 'cores/*_libretro*', 'VERSION.txt', 'README.md', 'LICENSES.md'],
        'retro.data': ['*-%s/*' % plat for plat in ['Genesis', 'Atari2600']],
    },
    package_dir={
        'retro.data': 'data'
    },
    setup_requires=['setuptools_scm'],
    use_scm_version=use_scm_version
)

## System information

- Ubuntu 16.04
- Python 3.6.3
- Gym Retro 0.5.4

**Comment by endrift** [comment]
Is your DNS and network set up properly?

**Comment by christopherhesse** [comment]
This issue is super old with no response from the user, closing.
