### ISSUE TITLE
subprocess.CalledProcessError: Command '['/usr/bin/make', '-j12', 'retro']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by SpacePython12** [openai/retro#280]
## Issue summary

When I try to install gym-retro with the command `pip3 install gym-retro`, the make task appears to fail when compiling Genesis Plus GX. Something about multiple definitions of the `config` and `zbank_memory_map` symbols.

## System information

- [Operating system] Linux (POP! OS 22.04)
- [Python version] 3.7, 3.8, 3.11
- [Gym Retro version] 0.7.11

**Comment by SpacePython12** [comment]
Whoops, forgot to attach logs. Hopefully this is enough.
[stderr.txt](https://github.com/openai/retro/files/11638233/stderr.txt)

**Comment by nonchris** [comment]
Hey, I've got the same error and issue. But I'm not sure if the build crashes at the same identical build.  
Running debian-bullseye with python 3.9

**Comment by nonchris** [comment]
Update.:
I manually installed python3.8 on my system and with 3.8 the install works fine.
So it's really a problem with later versions of python.

There is already an [issue](https://github.com/openai/retro/issues/274) for that open. So we should consider closing this one.
