### ISSUE TITLE
Unofficial installation Tips

### ISSUE THREAD

**Issue by shun1024** [openai/retro#35]
## Issue summary

Because of the lack of installation documentation, I was stuck at nothing for 3 hrs.

There is one straight and convenient way to install for the beginners. 

1. pip install gym-retro

2. create a steam account and buy the following game https://store.steampowered.com/app/71113/Sonic_The_Hedgehog/ 

3. python -m retro.import.sega_classics (this is to install the purchased games)

4. test with: https://contest.openai.com/details

- Ubuntu 16.04
- Python 3.6
- Retro 0.5.3

**Comment by castielblak** [comment]
Thank you, worked perfectly on Elementary 0.4.1 Loki.

**Comment by shun1024** [comment]
yes, this is the most convenient way

**Comment by Naereen** [comment]
I doubt that purchasing the Sonic game is mandatory to test this…

**Comment by christopherhesse** [comment]
I've updated the docs to use Airstriker-Genesis by default so people should just be able to run the examples directly, thanks for the feedback!
