### ISSUE TITLE
retro + PyTorch 0.4 import crash

### ISSUE THREAD

**Issue by pfrendl** [openai/retro#37]
## Issue summary

Importing both _torch_ and _retro_ causes a crash.

[Put a detailed description of the issue here.]

Minimal example:

**test.py**
```
import torch
import retro

```

Running _test.py_ causes a crash. There is no error message of note, I just get a "Python has stopped working" window with a single "Close program" button. If I end the _Windows problem reporting_ task from the task manager before this window appears, I get an _Application Error_ window reporting a memory access violation. I am not sure if this is what causes the crash or if this is caused by killing the problem reporting task.

The crash is also reproducible from the python JIT. Import order does not matter. Importing the packages from separate files also results in a crash.

## System information

Pytorch 0.4.0, CUDA 9.1, CUDNN 7.1
- [Operating system] Windows 10 x64
- [Python version] Python 3.6.4 (anaconda)
- [Gym Retro version] 0.5.4

**Comment by endrift** [comment]
does the order of the imports matter?

**Comment by pfrendl** [comment]
Import order does not matter.

**Comment by endrift** [comment]
I'll take a look when I get in tomorrow.

**Comment by endrift** [comment]
I believe this is an issue with pybind11, one of gym-retro's dependencies, not gym-retro itself, but it's hard to be sure.

**Comment by endrift** [comment]
This appears to either be an issue with PyTorch or pybind11. I built https://github.com/nschloe/pyfma for Windows (which also uses pybind11) and these programs crash:

```python
import torch
import retro
```
&
```python
import torch
import pyfma
```
But this doesn't:
```python
import pyfma
import retro
```

Please file this issue against PyTorch.
