### ISSUE TITLE
Can not find uncompressed ROMs folder

### ISSUE THREAD

**Issue by JunhongXu** [openai/retro#4]
## Issue summary

I just bought the whole SEGA Mega Drive and Genesis Classics on steam. When I executed `python -m retro.import.sega_classics` in command line and typed in my username and password correctly, I got the following error: 

> FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp4_y45_x7/uncompressed ROMs'

It seems that the downloading command does not download the ROMs correctly or the ROMs are downloaded into another directory? How can I fix this?

Thank you!

## System information

- OS: Ubuntu 16.04
- Python version: Python 3.6
- Retro version: 0.5.2

**Comment by JunhongXu** [comment]
Solved in a not so elegant way:
1. Download the ROMs based on using stream command line tools.
2. Execute the python command line.
3. Copy the ROMs to the tmp folder while the python process is running.

**Comment by cwgreene** [comment]
It seems to be installing successfully. I was able to copy (as per @JunhongXu suggestion) the files from .steam/steam/SteamApps/Sega\ Classics successfully. I hacked up the script in `site-packages/retro/scripts/import_sega_classics.py`

If you want to pause the program, just add input() right before the line containing `'uncompressed ROMS'`.

If you print out output.stdout right before it crashes, you get the interesting line:

```
Please set the game install path to something other than the Steam install folder
```

So it looks like somehow the `+force_install_dir` didn't work. Not familiar enough with how that works to know immediately how to fix it.

**Comment by wonseokjung** [comment]
HI @JunhongXu 

Do you mind if you explain more about number 1 ( ownload the ROMs based on Steam command line tools. ) 

I'm also using Ubuntu and bought the Rom. It doesn't let me download with python -m retro.import.sega_classics

**Comment by wonseokjung** [comment]
No such file or directory: '/tmp/tmpu6ik974q/uncompressed ROMs'

this is what I receive

**Comment by cwgreene** [comment]
@wonseokjung, it's installing the packages successfully, just not in the temp directory. In line 51 of this file:

https://github.com/openai/retro/blob/master/retro/scripts/import_sega_classics.py#L51

Put the following statements:

```
    print("Temporary Directory: ", dir)
    input()
```

When it prints the `Temporary Directory` location, copy the directory `.steam/steam/SteamApps/Sega\ Classics/uncompressed ROMs` into the tempoary directory.

And then resume the program.

**Comment by MrSyee** [comment]
@JunhongXu @cwgreene 
Hi.
I have a same problem.

I bought 'SEGA Mega Drive & Genesis Classics' on Steam, but I can't install the ROM on Ubuntu.
How do I install the ROM file? Please give me details about number one. (Download the ROMs based on Steam command line tools. )

**Comment by cwgreene** [comment]
That should work; steamcmd isn't great as far as documentation is concerned, and I don't know if it's source is available.
