### ISSUE TITLE
Reward is always 0.0

### ISSUE THREAD

**Issue by bgalbraith** [openai/retro#40]
## Issue summary

The reward returned by the environment is always 0.0 no matter what the agent does. Additionally, the done variable does not get set properly if the agent manages to complete the level. This suggests that the level x position is not being properly computed at some stage.

## System information

- [Operating system]
macOS 10.13.4
- [Python version]
3.6.5 (conda)
- [Gym Retro version]
gym-retro-0.5.5.dev9+g22c0f95

**Comment by endrift** [comment]
Are you using the right scenario file? Make sure you're using 'contest.json' and not 'scenario.json'.

**Comment by bgalbraith** [comment]
I figured it out. I was still using an old version of the code where I was importing `retro`, not `retro_contest.local` to make the environment. Thanks!
