### ISSUE TITLE
Discussion: Parallel Gym Environments

### ISSUE THREAD

**Issue by mancoast** [openai/retro#42]
Greetings!

First off, great work with the library and rapid advancement of AI environments for experimentation.

I have a few questions regarding parallel operation of the gym retro environments.

Is it possible to execute an array of environments with different games and stages simultaneously from within Python 3?  Are there any examples of this type of operation?

The end goal is to train (1) neural using a variety of games simultaneously.
Currently,  I initialize the environment, load the model in tensorflow, continue training the model, then save the model.  The process then repeats for a new game, but I am training the same model to play a variety different games.  Is it possible to operate on an array of gym retro environments within one tensorflow session?

Thanks,
Coast

**Comment by endrift** [comment]
It is possible but only with multi-process communication. Unfortunately the emulation backend we're using cannot be loaded into the same process more than once. @unixpickle can tell you more about how to do the IPC.

**Comment by unixpickle** [comment]
You can run multiple environments in parallel using a vectorized environment like [SubprocVecEnv](https://github.com/openai/baselines/blob/9cb7ece3387c4cb680fd831f38400b356bd599a6/baselines/common/vec_env/subproc_vec_env.py#L36). This creates a separate sub-process for each environment. You can also create a `gym.Env` that samples a different environment on every reset(), like [this JointEnv class](https://github.com/unixpickle/anyrl-py/blob/master/anyrl/envs/wrappers/meta.py#L104), for example.

**Comment by MaxStrange** [comment]
I wrote a drop-in wrapper for retro to allow me to do exactly this, for use with the A3C algorithm in Tensorflow. In case unixpickle's answers don't work for you @mancoast, it's an option: [retrowrapper](https://github.com/MaxStrange/retrowrapper). I just open-sourced it and stuck it in a repo.

**Comment by ChrisCates** [comment]
We should also allow manual reinforcement learning.
Let's say a certain video, sound, or action made you feel good... You should be able to use reinforcement learning to make it a positive or negative experience.

**Comment by ChrisCates** [comment]
I guess right now, that would just be taking notes... And, well, analyzing the environment. Since you'd also have to use recursion for everyone else.

**Comment by christopherhesse** [comment]
I'm thinking of closing this issue since it's more of a discussion topic.  Is there a better place to put this information?

**Comment by AloshkaD** [comment]
@MaxStrange I've been trying to parralize an custom openai gym env that uses the airsim, but Things aren't working for me. The airsim has a physics engine in unreal and that needs to run in order to return the states which are images and collision information. I appreciate any advice that will put me on the right track.
