### ISSUE TITLE
Adding a new NES game

### ISSUE THREAD

**Issue by ShaniGam** [openai/retro#49]
First of all, Great work!! Thank you :)
I want to add a new NES game that is currently not supported by your platform, how can I do that?
The name of the game is Road Fighter.
I tried importing the nes file by using the command: `python -m retro.import games/` and got `Imported 0 games`. What am I doing wrong?

**Comment by endrift** [comment]
Please see the integrator's guide: https://github.com/openai/retro/blob/develop/IntegratorsGuide.md

**Comment by ShaniGam** [comment]
Thank, but now I ran into another problem.
I compiled the Integration UI with no errors but unfortunately, the gym-retro-integration was not created.
