### ISSUE TITLE
Getting information for data file

### ISSUE THREAD

**Issue by ShaniGam** [openai/retro#54]
I want to add a new NES game and I'm trying to understand how to fill the data file.
I couldn't find an option to search for an address by value in your integration gui so I used a Hex Editor and found that the score is in 0x00005c-0x00005e. Is this the address? What do you mean by type?

**Comment by unixpickle** [comment]
The integration UI actually does have a way to search by value.

Type specifies the way the value is encoded in memory. For example, it might be little endian or big endian.

**Comment by ShaniGam** [comment]
@AurelianTactics @unixpickle Thank you for your help. I have 2 questions:
1. I understand now how to convert a hex address to the correct format, but what if I have more than one address for the score?
2. I wand to use the integrator tool in order to to find the type, how do I do that? What does it mean to search by variable or name?

**Comment by AurelianTactics** [comment]
1. You can combine multiple score addresses to use in a reward function in a lua script. See Sonic for an example of a reward function that relies on a lua script: https://github.com/openai/retro/blob/master/retro/data/stable/SonicTheHedgehog-Genesis/script.lua

2. I'm not super familiar with the Retro UI tool but I think it works like this. The bottom right part is a search tool and the top right is a watch tool. In the bottom right you search for variables that meet your criteria. Enter any name and then search by a criteria (ie it defaults to 'Is 0'). Hit search and then everything with value 0 appears (or whatever criteria you choose). Then you can click on the name in the Name/Found section. A bunch of different addresses that meet your criteria will appear in the Value/Address/Type section. Click on one of those addresses and then the 'Make Variable' button to make it into a variable. You can then watch that variable's information as the game plays out. Alternatively, you can make a variable to watch by inputting a name, address, and type in the 3 boxes above 'Scenario information.' In either section you can see the type.
