### ISSUE TITLE
Goes back to Sonic menu when life gets at zero

### ISSUE THREAD

**Issue by MatPoliquin** [openai/retro#58]
## Issue summary

When I am running locally Sonic doesn't reset to the predefined state when life goes to zero.
instead the game continues and goes back to main menu which screws the training because the algo (ppo, rainbow, etc) still thinks it's running in a level.

Details:
I am running the baseline script:
python3 ppo2_agent.py

I made the modifications to run locally as explained here:
[OpenAI contest details](https://contest.openai.com/details)

To **sonic_util.py**
added:
from retro_contest.local import make
changed:
#env = grc.RemoteEnv('tmp/sock')
env = make(game='SonicTheHedgehog2-Genesis', state='EmeraldHillZone.Act1', bk2dir='.')

## System information

- Ubuntu 18.04
- Python 3.6
-Gym-retro 5.6

**Comment by endrift** [comment]
Did you call env.reset when env.step returns done?

**Comment by MatPoliquin** [comment]
@morenfang You can get it from Steam for a small cost as explained on OpenAI's blog

**Comment by MatPoliquin** [comment]
@endrift 
env.reset() never gets called, but my question is why it doesn't reset when running locally?
As a temporary fix I manually call reset() and it  works but I want to know what is the root cause.

**Comment by morenfang** [comment]
@MatPoliquin get it~ thx!

**Comment by endrift** [comment]
What you're describing is not a bug. It is an error to call env.step after it returns done without calling env.reset. This is specified in the Gym API. The GymRemote version throws an exception if you try, but the local version doesn't really care.
