### ISSUE TITLE
Game not found: Adventure-Atari2600. Did you make sure to import the ROM?

### ISSUE THREAD

**Issue by SadAngelF** [openai/retro#60]
## Game not found: Adventure-Atari2600. Did you make sure to import the **ROM?**

[Put a detailed description of the issue here.]
lack ''rom.md''
## System information

- win10
- py35
-retro latest

**Comment by simoninithomas** [comment]
Hello, 
You need to import the roms they are not provided by default.


    Download zip file from http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html
    Open Roms.rar > ROMS.rar and find Space Invaders (1980) XXXXXX
    Extract all matches (there are 5 of them) into your destin folder
    python -m retro.import . (don't forget the point)
    One of them worked! And continue with the amazing tutorial here: https://github.com/simoninithomas/Deep_reinforcement_learning_Course/blob/master/DQN/Space%20Invaders/DQN%20Atari%20Space%20Invaders.ipynb

Taken from here https://github.com/openai/retro/issues/53

**Comment by SadAngelF** [comment]
@simoninithomas Thank you very much! That works. Yesterday I tried to find the ROMs, but I failed.

**Comment by waltdrexler** [comment]
> Hello,
> 
> ### **You need to import the roms they are not provided by default.**
> 1. Download zip file from http://www.atarimania.com/rom_collection_archive_atari_2600_roms.html
> 2. Open Roms.rar > ROMS.rar
> 3. Extract all
> 4. python -m retro.import . (don't forget the point)


Pls help a TRUE novice out: Where are we typing in the pythonmretroimport.  Right click the folder? command line, etc

**Comment by 8bitmp3** [comment]
> Pls help a TRUE novice out: Where are we typing in the pythonmretroimport. Right click the folder? command line, etc

@waltdrexler perhaps this "starter guide" I've put together can help and if there's an error maybe @endrift or @christopherhesse can point it out. Step 3 refers to importing ROMs.

You'll need to work in Jupyter (type your commands with a "!" in the cells) or use a command line (no need for "!").

1. If you haven't already, install `retro`:
```
pip install gym-retro
```
Alternatively, you can also git clone a fresh version of the repo with `git clone https://github.com/openai/retro.git` and then run `python setup.py install`. 

2. To run Sonic you should ideally get the game from Steam. Download the [Steam](http://store.steampowered.com/) app, create an account, purchase and download the game. The Retro Gym Contest run by OpenAI in 2018 worked on three version of Sonic: the original [Sonic The Hedgehog](http://store.steampowered.com/app/71113/Sonic_The_Hedgehog/), [Sonic 2](http://store.steampowered.com/app/71163/Sonic_The_Hedgehog_2/), and [Sonic 3 And Knuckles](http://store.steampowered.com/app/71162/Sonic_3___Knuckles/). You should get at least one of these games before moving on to the next step.

3. Once the game(s) are downloaded, import the game [ROMs](https://en.wikipedia.org/wiki/ROM_image) from the installed Steam directory, which hosts the Steam-purchased games, with: 
```
python -m retro.import '/STEAM-DIRECTORY-PATH/Steam'
```
(Note: on MacOS, the path would be somewhere under `'/Users/USER-NAME/Library/Application Support/Steam'`). The output should look like this:
> Importing 7422 potential games...
> Importing SonicAndKnuckles3-Genesis
> Importing SonicTheHedgehog2-Genesis
> Importing SonicTheHedgehog-Genesis
> Imported 3 games

Note: to list all supported game ROM environments before choosing the one(s) you have already: `retro.data.list_games()` (it's quite a long list).

4. The Sonic game environments you need to take note of are:
>  'SonicTheHedgehog-Genesis'
>  'SonicTheHedgehog-Sms'
>  'SonicTheHedgehog2-Genesis'
>  'SonicTheHedgehog2-Sms'
>  'SonicTheHedgehog3-Genesis'
>  'SonicTheHedgehogRandomLevels-Genesis'
I'd recommend using Genesis

5. Also, take note of the game levels (ignore ".state"—these are just the file types). You can view them all [here](https://github.com/openai/retro/tree/master/retro/data/stable/):
> GreenHillZone.Act1.state
> GreenHillZone.Act2.state
> GreenHillZone.Act3.state
> LabyrinthZone.Act1.state
> LabyrinthZone.Act2.state
> LabyrinthZone.Act3.state
> MarbleZone.Act1.state
> MarbleZone.Act2.state
> MarbleZone.Act3.state
> ScrapBrainZone.Act1.state
> ScrapBrainZone.Act2.state
> SpringYardZone.Act1.state
> SpringYardZone.Act2.state
> SpringYardZone.Act3.state
> StarLightZone.Act1.state
> StarLightZone.Act2.state
> StarLightZone.Act3.state

6. Test it with a nice viz of the game. First, check if you have matplotlib installed, and if not—"pip install matplotlib`. Add a cell in Jupyter or create a `sonic-rl-test.py` file:
```py
import retro
%matplotlib inline
import matplotlib as mpl # For visualization
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

# Instantiate the Sonic 1 environment and level 1 as follows:
env = retro.make(game='SonicTheHedgehog-Genesis', state='GreenHillZone.Act1')

obs = env.reset()

for i in range(100): # For 100 steps
    random_action = env.action_space.sample() # Take random actions
    obs, reward, done, info = env.step(random_action) # Progress the game (an agent's action is fed into `env.step()` and a new `obs` is sent to the agent)
    if done: 
        obs = env.reset() # Reset the environment if "game over" (done)

plt.imshow(obs)
```
Run it and you should see a snapshot of what the agent was up to.

7. Add `env.close()` to shut the environment's window and free up the resources.

8. Consider using a neat package called `retrowrapper` to run multiple instances of envs as subprocesses (`pip install retrowrapper`):
```
import retrowrapper

env_greehill_act1 = retrowrapper.RetroWrapper(
    game='SonicTheHedgehog-Genesis', 
    state='GreenHillZone.Act1')

env_labyrinth_act1 = retrowrapper.RetroWrapper(
    game='SonicTheHedgehog-Genesis', 
    state='LabyrinthZone.Act1')
```

**Comment by waltdrexler** [comment]
worked like a charm
