### ISSUE TITLE
Does retro support Super Mario (NES)

### ISSUE THREAD

**Issue by seungjaeryanlee** [openai/retro#61]
## Issue summary

I am trying to import the Super Mario environment from a `.nes` file but I get the following output:
```
Importing 0 potential games...
Imported 0 games
```

Does `gym-retro` not support NES rom files yet, or do I have an incorrect ROM?

## System information

- [Operating system] Ubuntu 16.04.4 LTS
- [Python version] Python 3.6.5 :: Anaconda, Inc.
- [Gym Retro version] gym-retro==0.5.6

**Comment by endrift** [comment]
You'll need to build 0.6 from master, which has NES support. There isn't a stable release of it yet though.

**Comment by seungjaeryanlee** [comment]
Guess I will have to wait until stable version of 0.6 comes out then! Thank you for the quick response :+1:
