### ISSUE TITLE
does not support centos 7

### ISSUE THREAD

**Issue by lucasliunju** [openai/retro#67]
## Issue summary

[Put a detailed description of the issue here.]

## System information

- [Operating system]
- [Python version]
- [Gym Retro version]

**Comment by endrift** [comment]
That's strange since it works on centos 5.

**Comment by christopherhesse** [comment]
I tested the wheel on a stock install of Centos 7 and I was able to create an environment and reset it.  Please reopen, @lucasliunju, if there are more details about this failure.
