### ISSUE TITLE
checking available environments

### ISSUE THREAD

**Issue by Kalsir** [openai/retro#69]
When using the provided code to check for available environments and starting states:
import retro
for game in retro.data.list_games():
    print(game, retro.data.list_states(game))

I get the error: module 'retro' has no attribute 'data'

However, it does work when I run:
import retro
for game in retro.list_games():
    print(game, retro.list_states(game))

**Comment by endrift** [comment]
This is the difference between 0.5.x (the current released version) and 0.6.x (currently in development, hopefully out soon).
