### ISSUE TITLE
Cannot Render Env

### ISSUE THREAD

**Issue by justusschock** [openai/retro#70]
## Issue summary
I just wanted to test the streetfighter genesis ROM and I am able to create an environment out of the ROM. If I try to render it or plot the state it looks like this:
![emulator](https://user-images.githubusercontent.com/12886177/44488394-ec80d880-a658-11e8-97d5-3351f57abcd8.png)

However if I try to open the ROM inside the UI-Integration it works out of the box.

Do you have any ideas why this happens?

## System information

- Ubuntu 18.04
- Python 3.7 (in conda environment)
- Gym Retro 0.6.0.dev45+g5af5926

**Comment by simoninithomas** [comment]
Hi,

Did you try to go forward 25 frames to see if it's the same frame ?

**Comment by simoninithomas** [comment]
Ok so the problem is different,
Did you download an american version of the rom ?
"We prefer the USA version of ROMs denoted by one of (USA), (USA, Europe), (Japan, USA), etc."

**Comment by justusschock** [comment]
Yes I downloaded the USA version and it works fine, if I try to start the ROM with the UI-Integration

**Comment by endrift** [comment]
Can you make sure the SHA1 matches the rom.sha file contents?

**Comment by justusschock** [comment]
I checked the SHA and it matches. I'll try to recompile and reinstall retro.

**Comment by simoninithomas** [comment]
@justusschock did you solve the problem ?

**Comment by simoninithomas** [comment]
Hi,
You speak about Street Fighter but it's not in the list of retro games.
**Did you speak about Street of Rage instead?**

**Comment by justusschock** [comment]
Hi,
No I'm talking about Street Fighter. It is in the list of games as ```StreetFighterIISpecialChampionEdition-Genesis```

**Comment by simoninithomas** [comment]
Hi,
Ok I don't have it in the list, ok I will make a test and see if I encounter the same bug.

**Comment by simoninithomas** [comment]
@justusschock how did you manage to install version 0.6.0? Because I can't test it with retro 0.5.6 and consequently I can't import this game.

**Comment by justusschock** [comment]
@simoninithomas I cloned the master branch and compiled/installed it from source.

**Comment by justusschock** [comment]
Got it working by redownloading the ROM although the previous one matched the sha1 sum

**Comment by BlkPingu** [comment]
where did you find the rom? @justusschock

**Comment by richoux** [comment]
@BlkPingu If you (or some other people) are still looking for it, you can find it in this GitHub repo: https://github.com/corbosiny/StreetFighterAI
