### ISSUE TITLE
import roms

### ISSUE THREAD

**Issue by michael20at** [openai/retro#71]
## Issue summary

Can't import roms.

[Put a detailed description of the issue here.]

I could install gym-retro with a windows wheel, but when I try to import roms (nes) it says:

"Importing 2 potential games"
"imported 0 games".

But no success in importing, any idea why?

## System information

- Win10
- Python 3.6
- Gym Retro Version 5.6

**Comment by endrift** [comment]
You probably have the wrong version of the ROMs or are trying to import ROMs for games with no integrations.

**Comment by michael20at** [comment]
They are standard nes roms (which should be supported by gym-retro and of which I have the original cartridge, so I guess that is ok? If not I will delete), US version. Tried it with another one, still no import, but rom plays fine in a normal emulator!

**Comment by endrift** [comment]
Gym Retro 0.5.x does not support NES games. You'll need to use 0.6, which does not have a binary package available for on PyPI yet. You can download a dev build here: 
https://storage.googleapis.com/gym-retro/builds/gym_retro-0.6.0.dev45%2Bg5af5926-cp36-cp36m-win_amd64.whl
