### ISSUE TITLE
retro.data has no attribute list_games

### ISSUE THREAD

**Issue by dhanush987** [openai/retro#74]
I am trying below and get this issue:

>>> import retro
>>> retro.data.list_games()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'retro.data' has no attribute 'list_games'
>>> 

Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux

I installed using pip install gym-retro. Shouldnt data files be already present ?

**Comment by endrift** [comment]
pip does not have the latest gym-retro version; I'm going to be fixing that tomorrow. For 0.5 just remove the `.data` from that.
