### ISSUE TITLE
No in-game sound

### ISSUE THREAD

**Issue by axfcampos** [openai/retro#76]
## Issue summary

When rendering a game (e.g. Super Mario Bros.) using `env.render()` I get no in-game sound.

I'm not sure if its supposed to have sound. If this is not a bug could you point me in the right direction? I would like to implement this my self, even if it doesn't get accepted, I'd like to use it. If it is a bug, same request :smile:. Thank you.

## System information

- Ubuntu 18.04.1 LTS
- Python 3.6.5
- https://github.com/openai/retro/commit/684bd5f3db8a493a3a4c411f0654474e7af980ee

**Comment by endrift** [comment]
You can access the sound data directly (`env.em.get_audio` and `env.em.get_audio_rate`) but it's not hooked up to anything at the moment, somewhat due to a lack of good APIs for this.

**Comment by christopherhesse** [comment]
I think this could be implemented as an option to the retro environment (or as a wrapper for now in some third-party code).  You could expose the audio data along side the visual observation at each frame with some dictionary observation space, `rgb` and `audio`

**Comment by christopherhesse** [comment]
@axfcampos did you end up doing anything with the audio data?

**Comment by endrift** [comment]
@christopherhesse the problem with that approach is that the `audio` data isn't always the same length, for some cores it's ±1 sample, for others it can be much larger.

**Comment by christopherhesse** [comment]
Oh interesting, can we pad to the max length?

**Comment by endrift** [comment]
Bad idea, that leads to clicking

**Comment by christopherhesse** [comment]
Oh my bad, I thought this was audio for RL not for the render method.

**Comment by axfcampos** [comment]
Hi @christopherhesse @endrift 
> @axfcampos did you end up doing anything with the audio data?

Yes, my goal was to observe learning in real time with the actual in-game sound.
First thing I did was on each `step` send `env.em.get_audio` to a different thread and in that thread I piped the sound to ffmpeg and then to ffplay, then I wrapped the `step` function to `render` at 60 steps per second (so the video doesn't go faster than the sound).

Not sure if it would be useful, I can share the code if you'd like (not a lot, ~90 loc and straighforward), 

This is a clip of it working: https://www.twitch.tv/tobit_/clip/InquisitiveDignifiedLionMVGame
I've been streaming different experiments on that channel :smile:

**Comment by christopherhesse** [comment]
You can share the code if you want here in case someone else wants to use it but it sounds like we might not integrate this feature into gym-retro at this time.

**Comment by christopherhesse** [comment]
Since we don't currently have plans to add sound to the viewer I will close this.

**Comment by OhRly-net** [comment]
@axfcampos would you mind sharing the code to get sound working please?

**Comment by axfcampos** [comment]
I don't mind at all... but only next week, it's in a computer I'm not close to atm and I never pushed it to a remote ☹️

**Comment by rbanks721** [comment]
Where can I find the code for this?

**Comment by yanpanlau** [comment]
I kinda make it work by using simpleaudio package and open a seperate thread to play the sound. However, the current fps (1/90.0) is set by hand. Do you guys have any idea how can I automatic set the time.sleep() such that the video and the audio are in-sync?

```import retro
import time
import simpleaudio as sa
from threading import Thread
import numpy as np

class sound():
    def play(self, array, fs):
        sa.play_buffer(array, 2, 2, 44100)


def main():
    env = retro.make(game='StreetFighterIISpecialChampionEdition-Genesis')
    obs = env.reset()
    count = 0
    while True:
        obs, rew, done, info = env.step(env.action_space.sample())
        time.sleep(1.0/90.0)
        env.render()
        a = env.em.get_audio()
        b = env.em.get_audio_rate()
        thread = Thread(target = mysound.play, args=(a,b,))
        thread.start()
        if done:
            obs = env.reset()
    env.close()


if __name__ == "__main__":
    mysound = sound()
    main()

**Comment by gxc8311** [comment]
I made it work using the code that looks like something below. it sounds pretty close to something that comes out of an emulator, without any noticeable hiccups. Enjoy~

```
import time
import retro

# you need to run 'pip install pyaudio' first in command line, in order to import pyaudio
import pyaudio

frame_time = 1.0 / 60.0
recording_video = True

def get_time():
    return time.time()

def main():
    p = pyaudio.PyAudio()
    stream = p.open(format=pyaudio.paInt16,
                    channels=2,
                    rate=44100,
                    output=True)

    last_time = get_time()
    
    env = retro.make(game='StreetFighterIISpecialChampionEdition-Genesis')
    obs = env.reset()
    count = 0
    while True:
        obs, rew, done, info = env.step(env.action_space.sample())

        # make sure every frame is of length 1/60s
        current_time = get_time()
        time_diff = current_time - last_time
        if time_diff < frame_time:
            time.sleep(frame_time - time_diff)
        last_time = current_time
        
        env.render()
        
        # play audio sample for this frame
        a = env.em.get_audio()
        b = env.em.get_audio_rate()
        bytes_array = a.flatten().astype('int16')
        frames_count = len(a)
        stream.write(frames=bytes_array, num_frames=frames_count)

        if done:
            obs = env.reset()
            
    env.close()
    
    # close audio stream
    stream.close()
    p.terminate()


if __name__ == "__main__":
    main()
```
