### ISSUE TITLE
MultiBinary action space in NES game

### ISSUE THREAD

**Issue by ShaniGam** [openai/retro#77]
I'm working with a game that has a Multi-Binary action space (with 9 spots). Where can I find a documentation that explains what each action does?

**Comment by endrift** [comment]
Each of the indices corresponds to the buttons listed here: https://github.com/openai/retro/blob/master/cores/nes.json#L6. Note that one of them is null--this is due to the way the libretro backend is designed, so you can safely discard values in that index.

**Comment by ShaniGam** [comment]
Thanks!
