### ISSUE TITLE
Rew variable always returns 0

### ISSUE THREAD

**Issue by MatPoliquin** [openai/retro#78]
## Issue summary
After Mario jumps on a goomba "info" returns a score of 10
but "rew" still returns 0

Here is the code:

def main():
    env = retro.make(game='SuperMarioBros3-Nes', state='1Player.World1.Level1')
 
    obs = env.reset()
    while True:
        obs, rew, done, info = env.step(env.action_space.sample())
        print(info)
        print(rew)
        env.render()
        if done:
            obs = env.reset()

## System information

- [Operating system]
Ubuntu 18.04
- [Python version]
3.6.5 64bit
- [Gym Retro version]
0.6

**Comment by endrift** [comment]
Reward is the delta, so it should return non-zero once per change of the variable in the info dict. random_agent.py indicates that this does happen, so I can't reproduce.

**Comment by MatPoliquin** [comment]
Thanks for the answer, it was a mistake on my side, it works now
