### ISSUE TITLE
Manually Importing ROM

### ISSUE THREAD

**Issue by axhue** [openai/retro#8]
## Issue summary

I have a few ROMs in .md format in my home directory, how can I manually import this ROM?

Awesome work! Super excited about this! :smile: 

## System information

- [Ubuntu 14.04]
- [3.5.2]
- [Gym Retro 0.5.2]

**Comment by axhue** [comment]
Sorry I just figured it out!

For other users run `python -m retro.scripts.import_path .` in the ROM directory

**Comment by endrift** [comment]
`python -m retro.import .` should work too, being an alias for the above.
