### ISSUE TITLE
I can't import Nintendo Super Mario at present on Win10

### ISSUE THREAD

**Issue by dbsxdbsx** [openai/retro#80]
At present, I just install retro through `pip install gym-retro`， and the version is 0.6. But seems it is still not working, the error is like #61.

**Comment by endrift** [comment]
Are you sure you have the right ROM? Double check that the SHA-1 matches the contents of the rom.sha for that game.

**Comment by endrift** [comment]
Oh! I should fix that so you can pass filenames too.
