### ISSUE TITLE
Help needed: Error while installing gym-retro using pip3

### ISSUE THREAD

**Issue by BhayanakMoth** [openai/retro#83]
I am getting the following error:
Edit:
In Text:
-- Found PythonInterp: c:\python3\python.exe (found version "3.6.3")
    -- The C compiler identification is Clang 8.0.0
    CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/CMakeDetermineCompilerId.cmake:771 (message):
      The Clang compiler tool

        "C:/Program Files/LLVM/bin/clang.exe"

      targets the MSVC ABI but has a GNU-like command-line interface.  This is
      not supported.  Use 'clang-cl' instead, e.g.  by setting 'CC=clang-cl' in
      the environment.  Furthermore, use the MSVC command-line environment.
    Call Stack (most recent call first):
      C:/Program Files/CMake/share/cmake-3.11/Modules/CMakeDetermineCCompiler.cmake:113 (CMAKE_DIAGNOSE_UNSUPPORTED_CLANG)
      CMakeLists.txt:23 (project)

    CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Laptop/AppData/Local/Temp/pip-install-4hmsibe2/gym-retro/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Laptop\AppData\Local\Temp\pip-install-4hmsibe2\gym-retro\setup.py", line 90, in <module>
        **kwargs
      File "c:\python3\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python3\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\python3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python3\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python3\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\python3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\python3\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\python3\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python3\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Laptop\AppData\Local\Temp\pip-install-4hmsibe2\gym-retro\setup.py", line 53, in run
        subprocess.check_call([cmake_exe, '.', '-G', 'Unix Makefiles', build_type, pyext_suffix, pylib_dir, python_executable])
      File "c:\python3\lib\subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.exe', '.', '-G', 'Unix Makefiles', '', '-DPYEXT_SUFFIX:STRING=.cp36-win32.pyd', '-DPYLIB_DIRECTORY:PATH=build\\lib.win32-3.6', '-DPYTHON_EXECUTABLE:STRING=c:\\python3\\python.exe']' returned non-zero exit status 1.

    ----------------------------------------
Command "c:\python3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Laptop\\AppData\\Local\\Temp\\pip-install-4hmsibe2\\gym-retro\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Laptop\AppData\Local\Temp\pip-record-b1fzmjeb\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Laptop\AppData\Local\Temp\pip-install-4hmsibe2\gym-retro\

## System information

- Windows 10 x64
- Python 3.6.3
- Gym Retro 0.6.0

**Comment by TheSentry** [comment]
Why are you posting screenshots instead of copying the text? That would make it much easier to read and to search in it.

**Comment by endrift** [comment]
You don't want clang-cl, that's for generating MSVC binaries, which are not supported. Further, it can't find a C++ compiler.

**Comment by BhayanakMoth** [comment]
That's strange because I have 3 different C++ compilers. Do I have to set the directory to C++ and C compiler manually?

**Comment by BhayanakMoth** [comment]
> You don't want clang-cl, that's for generating MSVC binaries, which are not supported. Further, it can't find a C++ compiler.

Which compiler should I be using? Will GCC work?

**Comment by endrift** [comment]
Yes, gcc (MinGW) should work.

**Comment by BhayanakMoth** [comment]
extracting the tar file to a directory and running cmake gives me these errors:
[log1.txt](https://github.com/openai/retro/files/2412065/log1.txt)

**Comment by BhayanakMoth** [comment]
> 
> 
> Yes, gcc (MinGW) should work.

extracting the tar file to a directory and running cmake gives me these errors:
[log1.txt](https://github.com/openai/retro/files/2412065/log1.txt)
Can't make out any sense of what they are except for the part where I am missing something.
