### ISSUE TITLE
CMake cannot copy output executable due to missing executables

### ISSUE THREAD

**Issue by BhayanakMoth** [openai/retro#84]
## Issue summary

I am getting this error when I install gym-retro from pip:
[log1.txt](https://github.com/openai/retro/files/2412395/log1.txt)

## System information

- Windows 10 x64
- Python 3.6.3
- 0.6.0

**Comment by endrift** [comment]
I think something is wrong with your CMake, but it's...very hard to tell. Please upload the error log too.

**Comment by BhayanakMoth** [comment]
Ran pip install setup.py after extracting tarball. This is the error log:
[CMakeError.log](https://github.com/openai/retro/files/2413560/CMakeError.log)

**Comment by BhayanakMoth** [comment]
Welp, I got it working on Ubuntu. If I find a proper solution then I will post it here.
