### ISSUE TITLE
Question: Can I use data.json to return something else other than info?

### ISSUE THREAD

**Issue by BhayanakMoth** [openai/retro#85]
Can I do something like this?
{
  "info": {
    "gameover": {
      "address": 83,
      "type": "|i1"
    },
    "lives": {
      "address": 41,
      "type": "|i1"
    },
    "score": {
      "address": 34,
      "type": "<u2"
    }
            
  },
"pulseX": [{
              "address": 1815,
              "type":"|i1"
             },{
               "address": 1815,
              "type":"|i1"
             }]
   
 
}
Also can I ask such questions here or is there a separate channel for such discussion?

**Comment by endrift** [comment]
I don't know of a better place to ask this.

I'm not sure what you're trying to accomplish here though.

**Comment by christopherhesse** [comment]
@BhayanakMoth you can certainly define more variables, but you should do them under the "info" dictionary.  They'll show up in the `info` dict returned from `env.step()` this way.
