### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Bestchoice233** [openai/retro#90]
## Issue summary

I tried both binary installation and source installation but when I type import retro in python, it says "No module named retro" like the following:

     import retro
     Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     ModuleNotFoundError: No module named 'retro'

When I cd to the folder **gym-retro** and run **pip3 install -e .**, it throws the following error:

    In file included from mednafen/pce_fast/huc6280.cpp:18:
    In file included from mednafen/pce_fast/pce.h:4:
    mednafen/pce_fast/../mednafen-types.h:4:10: fatal error: 'assert.h' file not found
    #include <assert.h>
             ^~~~~~~~~~
    In file included from src/arm/arm.c:6:
    In file included from ./include/mgba/internal/arm/arm.h:9:
    ./include/mgba-util/common.h:19:10: fatal error: 'ctype.h' file not found
    #include <ctype.h>
             ^~~~~~~~~
    core/cd_hw/libchdr/src/bitstream.c:13:10: fatal error: 'stdlib.h' file not found
    #include <stdlib.h>
             ^~~~~~~~~~
    In file included from src/boards/01-222.c:36:
    In file included from src/boards/mapinc.h:3:
    In file included from src/boards/../fceu.h:71:
    src/driver.h:4:10: fatal error: 'stdio.h' file not found
    #include <stdio.h>
             ^~~~~~~~~
    1 error generated.
    1 error generated.
    1 error generated.
    In file included from libgambatte/src/bootloader.cpp:2:
    In file included from /Library/Developer/CommandLineTools/usr/include/c++/v1/cstring:61:
    /Library/Developer/CommandLineTools/usr/include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    make[4]: *** [core/cd_hw/libchdr/src/bitstream.o] Error 1
    make[4]: *** [src/arm/arm.o] Error 1
    make[4]: *** [src/boards/01-222.o] Error 1
    In file included from stella/src/common/Base.cxx:20:
    stella/src/common/Base.hxx:23:10: fatal error: 'iostream' file not found
    #include <iostream>
             ^~~~~~~~~~
    make[3]: make[3]: *** [retro/cores/fceumm_libretro.dylib] Error 2*** [retro/cores/mgba_libretro.dylib] Error 2

    make[3]: *** [retro/cores/genesis_plus_gx_libretro.dylib] Error 2
    ../apu/apu.cpp:190:10: fatal error: 'math.h' file not found
    make[2]: #include <math.h>
    *** [CMakeFiles/genesis.dir/all] Error 2         ^~~~~~~~

    make[2]: *** Waiting for unfinished jobs....
    make[2]: *** [CMakeFiles/nes.dir/all] Error 2
    make[2]: *** [CMakeFiles/gba.dir/all] Error 2

The above is just one part of the error it throws. I do have **cmake** installed, still I don't know how to solve this issue. 

## System information

- MacOS Mojave
- Python 3.6.5
- Gym Retro version: current version

**Comment by endrift** [comment]
Run `xcode-select --install`.

**Comment by endrift** [comment]
Install `/Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` and try the `mojave-buildfix` branch.

**Comment by christopherhesse** [comment]
@Bestchoice233 did the mojave branch work for you?

**Comment by endrift** [comment]
The Mojave branch got merged, so it's only the pkg that's relevant anymore.

**Comment by christopherhesse** [comment]
Oh so you mean that most users will need to install that before building from source will work?

**Comment by endrift** [comment]
I'm not sure. I know I had to, but I've seen people who don't.

**Comment by christopherhesse** [comment]
No response from the issue creator for awhile, closing this issue.
