### ISSUE TITLE
Please upgrade auditwheel to 1.9

### ISSUE THREAD

**Issue by ehashman** [openai/retro#91]
## Issue summary

Auditwheel is currently pinned to version 1.8.0:

https://github.com/openai/retro/blob/ae951df3806d8068a5d549a83c0fb91675aaed35/docker/linux/build_scripts/py36-requirements.txt#L6

A newer release 1.9.0 is available (and soon 1.10.0 which I should be releasing in the next week or two). Would you please considering upgrading auditwheel and letting me know if everything still works alright?

## System information

N/A

**Comment by endrift** [comment]
Done. Everything seems to work fine.

**Comment by ehashman** [comment]
Great thanks!
