### ISSUE TITLE
Could not connect to display

### ISSUE THREAD

**Issue by jhpenger** [openai/retro#92]
## Issue summary

On a GCE headless instance
I get the following error when attempting to install from source on this command:
`./gym-retro-integration`
Error Msg: 
```
QXcbConnection: Could not connect to display 
Aborted
```

## System information

- [Operating system] Debian GNU/Linux 9 (stretch) on GCloud Engine
- [Python version] 3.6.5
- [Gym Retro version] 0.6.0

**Comment by endrift** [comment]
The integration tool is a GUI. You can't use it headless. Gym Retro itself doesn't require the integration tool.
