### ISSUE TITLE
Where can I get the SuperMarioBros-Nes ROM?

### ISSUE THREAD

**Issue by Silence1995** [openai/retro#93]
## Issue summary

I get the error like this when i try to make the env for training mario

![image](https://user-images.githubusercontent.com/19864558/48264788-b425b500-e465-11e8-8314-a2f108d55120.png)

Thanks

## System information

- [Ubuntu16.04]
- [Python 3.5.2]
- [Gym Retro 0.6.1]

**Comment by christopherhesse** [comment]
Sorry, as stated in the docs:

"Please note that ROMs are not included and you must obtain them yourself."
https://github.com/openai/retro#gym-retro

**Comment by QuarTerll** [comment]
Finally, I find that here 
[https://wowroms.com/en/roms/nintendo-entertainment-system/download-super-mario-bros./23755.html]

Just unzip this file, and rename it as rom.nes.
Then put it into the folder of Super Mario Bro. 

![b4e885675fb2b3782113b61d27881dd](https://user-images.githubusercontent.com/49419815/55888856-094a2c00-5ba8-11e9-82e5-ed4708a056ac.png)

And run code like below to test.

![image](https://user-images.githubusercontent.com/49419815/55889255-bc1a8a00-5ba8-11e9-9244-467682e638ce.png)

Hope this can help you !
Now go to code your own AI.

**Comment by christopherhesse** [comment]
@QuarTerll sorry, please do not link to ROM websites
