### ISSUE TITLE
import retro fails on Colabra

### ISSUE THREAD

**Issue by dpthayer** [openai/retro#94]
## Issue summary
In Colabra I am running the following command 
!pip install -U retro
Which gives the following output:
Collecting retro
  Downloading https://files.pythonhosted.org/packages/f8/fa/daf029d4cb4cea8960c1ae236b75beef9cb90838a77316fe71087e2c78e6/Retro-0.9.5.tar.gz
Building wheels for collected packages: retro
  Running setup.py bdist_wheel for retro ... done
  Stored in directory: /root/.cache/pip/wheels/c2/9c/7f/8368f0790793f3d0d910e0ccff47beba8fd8e2d16da9b26846
Successfully built retro
Installing collected packages: retro
Successfully installed retro-0.9.5

In the next cell I execute the following code.
import retro

I am then getting a syntax error 
File "/usr/local/lib/python3.6/dist-packages/retro/__init__.py", line 206
    print "%s: %s" % (key, value)
                 ^
SyntaxError: invalid syntax

## System information

-Unknown probably some version of linux
- Python 3.6.6
- retro 0.9.5

**Comment by endrift** [comment]
You have to pip install gym-retro. Retro is a different project.
