### ISSUE TITLE
 [question] How do you add multiple boxes to an observation space?

### ISSUE THREAD

**Issue by wilkinsmicawber** [openai/retro#96]
In all the examples I've seen, only a single box type has been added to the observation space. I would like to add two boxes, one for pixel information, another for ram information. Is this possible?

My motivation comes from thinking that, if sonic knows his velocity every frame, he has a much better overall picture of the situation than just knowing the inputs and pixel information.

I'm using the rainbow tensorflow DQN baseline. Perhaps this is one of those cases where knowing more about tensorflow would be beneficial. Not sure if I should be feeding in the ram data to one of the tensorflow script arrays or focusing on expanding the observation space.

**Comment by endrift** [comment]
This isn't possible. Adding velocity can be done into the info dict however.

**Comment by wilkinsmicawber** [comment]
The info dict is processed as an input to the neural network, ay? I'm guessing it has nothing to do with the Lua data array. Can't find where the DataGlue class is, otherwise I might be able to dig further into it.

**Comment by endrift** [comment]
It's in retro.cpp. You can modify the integration to extract the velocity. What you do with the info dict is up to your implementation.
